New rule: TryCatchFinallyExpression
detekt/detekt pull request #3228
Opened 2020-11-12 20:32 UTC by rwqwr

Fixes https://github.com/detekt/detekt/issues/3197

2020-11-12 20:42 UTC, schalkms requested changes
Thanks for tackling this issue! 🙂
It's a really nice 1st contribution to detekt. 

Please note, that there's already an existing rule. The following rule should be adapted to handle this case. There's no need for a new rule. Otherwise, this is very confusing for users of detekt.
Please take a look at the following class.
https://github.com/detekt/detekt/blob/master/detekt-rules-exceptions/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/ReturnFromFinally.kt

Please kindly let me know, if you have any questions.

2020-11-15 20:28 UTC, rwqwr commented
Thank you for your response! 🙂
I fixed this moment and implemented this case in `ReturnFromFinally` rule.

2020-11-15 22:54 UTC, schalkms reviewed
Thanks for incorporating the changes! This PR looks good.
The mentioned refactoring can also be done in a separate PR, if you want.

2020-11-15 22:54 UTC, schalkms commented on detekt-rules-exceptions/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/ReturnFromFinally.kt
> + * See: https://kotlinlang.org/docs/reference/exceptions.html#try-is-an-expression
This might be better understandable to first time users of this rule.

```suggestion
 * Reports all `return` statements in `finally` blocks.
 * Using `return` statements in `finally` blocks can discard and hide exceptions that are thrown in the `try` block.
 * 
 * Furthermore, this rule reports values from `finally` blocks, if the corresponding `try` is used as an expression.
```

2020-11-15 22:54 UTC, schalkms commented on detekt-rules-exceptions/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/ReturnFromFinally.kt
> +        if (expression.isUsedAsExpression(bindingContext) && finallyBlock != null) {
This statement can be switched, since the usage of `bindingContext` in this case could be more expensive.

```suggestion
        if (finallyBlock != null && expression.isUsedAsExpression(bindingContext)) {
```

2020-11-15 22:54 UTC, schalkms commented on detekt-rules-exceptions/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/ReturnFromFinally.kt
>      }
Maybe the logic from `visitFinallySection()` can
* be merged together with `visitTryExpression()`
* use the `bindingContext` capability as well.

This would reduce the complexity of this rule.

2020-11-18 20:17 UTC, rwqwr commented
I refactored code and changed the implementation of `visitFinallySection()` with the `bindingContext` capability, but left the check inside it. It seemed to me more correct.

2020-11-18 21:01 UTC, schalkms commented on detekt-rules-exceptions/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/ReturnFromFinally.kt
> +            .toList()
Is this mandatory?

2020-11-18 21:01 UTC, schalkms commented on detekt-rules-exceptions/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/ReturnFromFinally.kt
> +        val targetFunction = returnStmts.getTargetFunction(bindingContext)
I guess we also need to check for an empty binding context here.

2020-11-18 21:01 UTC, schalkms commented on detekt-rules-exceptions/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/ReturnFromFinallySpec.kt
> +                }
Unfortunately, the formatting seems to be off here.

2020-11-18 21:02 UTC, schalkms commented
Thanks! We also need to add a `@requireTypeResolution` annotation to the rule comment, since type and symbol solving needs to be configured.

2020-11-18 21:43 UTC, rwqwr commented on detekt-rules-exceptions/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/ReturnFromFinally.kt
> + * @requiresTypeResolution
> We also need to add a `@requireTypeResolution` annotation to the rule comment, since type and symbol solving needs to be configured.

Do you mean this annotation?

2020-11-18 21:44 UTC, rwqwr commented on detekt-rules-exceptions/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/ReturnFromFinally.kt
> +        val targetFunction = returnStmts.getTargetFunction(bindingContext)
I added check to `visitFinallySection()`
Is it ok?

2020-11-18 21:45 UTC, rwqwr commented on detekt-rules-exceptions/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/ReturnFromFinallySpec.kt
> +                }
Sorry, it is my mistake :)

2020-11-18 21:48 UTC, rwqwr commented on detekt-rules-exceptions/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/ReturnFromFinally.kt
> +            .toList()
`blockExpressionsOrSingle()` extension return `Sequence<KtElement>` and `isInsideOf` take `Iterable<PsiElement>` as argument.

2020-11-19 10:59 UTC, schalkms commented on detekt-rules-exceptions/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/ReturnFromFinally.kt
> + * @requiresTypeResolution
Exactly

2020-11-19 11:00 UTC, schalkms approved these changes

2020-11-19 11:01 UTC, merged