Add MultilineLambdaItParameter rule
detekt/detekt pull request #3259
Opened 2020-11-29 15:11 UTC by adamkobor

This new rule checks if there is any multiline lambda with a parameter called `it` (whether it's an implicit or an explicit one, it doesn't matter).

2020-11-29 16:36 UTC, cortinico commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt
> + * }
I believe this rule is a bit too strict.
I think we should report only lambda that contains actually more than one line (and not checking for `\n`). 

The reason is that I think detekt should treat:

```
val digits = 1234.let {
    listOf(it)
}
```

and

```
val digits = 1234.let { listOf(it) }
```

equivalent. Otherwise this becomes more a rule for the formatter (like `ktlint`).

I think we should rather report lambdas like this one:

```
val digits = 1234.let {
	println(it)
    listOf(it)
}
```

2020-11-29 16:40 UTC, cortinico reviewed
Thanks for your contribution @adamkobor.
I'd love to hear other members feedback on the idea behind your rule. I'm also wondering if we should merge the behavior inside the `ExplicitItLambdaParameter` rule and treat this as a config option.

2020-11-29 16:40 UTC, cortinico commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt
> +                    "The parameter name in a multiline lambda should not be an implicit/explicit `it`"
```suggestion
                    "The parameter name in a multiline lambda should not be an implicit/explicit `it`. Consider giving your parameter a name"
```

2020-11-29 16:40 UTC, cortinico commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameterSpec.kt
> +                }""")
I'd suggest you extract the source code to:

```suggestion
            val code = """
                fun f() {
                    val digits = 1234.let { 
                        listOf(it)
                    }
                }
            """
```

And use `code` to invoke `compileAndLint` afterwards. It makes the test easier to read.

2020-11-29 16:54 UTC, adamkobor commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameterSpec.kt
> +                }""")
Makes sense, will fix it 👍

2020-11-29 17:46 UTC, adamkobor commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt
> + * }
Fair enough, I agree that reporting lambdas that are wrapped into multiple lines but only contains a single statement is a bit too strict.

> Thanks for your contribution @adamkobor.
> I'd love to hear other members feedback on the idea behind your rule. I'm also wondering if we should merge the behavior inside the `ExplicitItLambdaParameter` rule and treat this as a config option.

Thanks! Initially, I was thinking about the same (extending `ExplicitItLambdaParameter` somehow), but it seems like a quite different rule for me, speaking of what it wants to enforce. Even if we could merge the two, it would be very hard to find a good name for the new rule IMO :) 
However, I'm open to any kind of suggestion about this if you have a better idea 🙌

2020-11-29 17:47 UTC, adamkobor commented
> Thanks for your contribution @adamkobor.
> I'd love to hear other members feedback on the idea behind your rule. I'm also wondering if we should merge the behavior inside the `ExplicitItLambdaParameter` rule and treat this as a config option.

Thanks! Initially, I was thinking about the same (extending `ExplicitItLambdaParameter` somehow), but it seems like a quite different rule for me, speaking of what it wants to enforce. Even if we could merge the two, it would be very hard to find a good name for the new rule IMO :) 
However, I'm open to any kind of suggestion about this if you have a better idea 🙌

2020-11-29 22:14 UTC, BraisGabin commented
Nice rule!

I think that they are different rules. We need new buckets to define rules because this one helps readability but the other just removes redundant code. 

I would keep this one as a different rule.

And should we care if the code defines the parameter as `it`? It's just an open question. I have no idea which one is the bette option.

2020-12-14 17:43 UTC, chao2zhang requested changes

2020-12-14 17:43 UTC, chao2zhang commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt
> + * Lambda expressions are are very useful in a lot of cases and they often include very small chunks of
```suggestion
 * Lambda expressions are very useful in a lot of cases and they often include very small chunks of
```

2020-12-14 17:43 UTC, chao2zhang commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt
> + *
My team also found it not readable to replace `it` parameters with poor names that are too abstract. Such as `data`, `obj` etc. I think should call it out to replace `it` with descriptive and readable names.

I would also recommend replacing the issue message by `Multiline lambdas should use a descriptive name rather than it as the parameter name`

2020-12-14 17:43 UTC, chao2zhang commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt
> + * }
These are actually code smells, right? https://github.com/detekt/detekt/blob/master/detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExplicitItLambdaParameter.kt

2020-12-14 17:43 UTC, chao2zhang commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt
> + * }
`IT_LITERAL in parameterNames` is already checked in the rule mentioned above, so we don't need to `double report`

2020-12-21 12:57 UTC, adamkobor commented
Sorry for the late answer, I will look into this in the coming days, but we have family issues right now at home with our newborn, so my time is quite limited :)

2020-12-30 12:21 UTC, adamkobor commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt
> + * }
Thanks, I totally agree that these rules actually have some overlap, but I think their perspective are quite different. Therefore, I wouldn't remove this overlap, because it's possible that someone is using only one of them. What do you think?

2020-12-30 12:21 UTC, adamkobor commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt
> + *
Makes sense, I've updated the doc block and the issue message as well.

2021-01-05 18:22 UTC, cortinico commented
> but we have family issues right now at home with our newborn, so my time is quite limited :)

Sure take your time :) If you need some help just drop us a message

2021-01-06 00:54 UTC, chao2zhang commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameter.kt
> + * }
People may enable both rules, and they may get double issues...

That could be our expectation since abusing `it` is lowering the readability significantly.
I am okay with keeping it as is.

2021-01-06 09:53 UTC, adamkobor commented
> > but we have family issues right now at home with our newborn, so my time is quite limited :)
> 
> Sure take your time :) If you need some help just drop us a message

Thanks @cortinico, I already made the adjustments you and @chao2zhang requested, so if you have some time, please take a look at it :)

2021-01-06 20:51 UTC, cortinico commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MultilineLambdaItParameterSpec.kt
> +                assertThat(findings).hasSize(0)
```suggestion
                assertThat(findings).isEmpty()
```

2021-01-07 13:52 UTC, adamkobor commented
> Other than minor comments, LGTM 👍

Thanks, I also applied your suggestions 🙌

2021-01-08 18:56 UTC, chao2zhang approved these changes

2021-01-10 15:07 UTC, cortinico approved these changes

2021-01-14 15:11 UTC, merged