Support configurable severity per ruleset/rule in XML and Sarif output
detekt/detekt pull request #3310
Opened 2020-12-20 03:48 UTC by chao2zhang

Summary
=======
This PR implements configuring the severity in the XML and Sarif output, which is the first step to implement #3274. The implementation is also different from #3306, because the severity in the configuration can only be a simplified version and does not allow custom strings.

Implementation
===========
Adding the `severity` as a property of `Issue` does not work: Each rule initializes the `issue` first then uses the `issue.id` to initialize `ruleConfig`. If we want to use `ruleConfig` to parse `severity`, it has to be done after `issue` is created.
We can break such cycling dependency by refactoring, but I would prefer doing so in the next PR where we can remove the existing `Severity` and replace it with the new `SeverityLevel`.

The choice here is to add the `severity` as a property of `Finding`, which is appended at the end to mitigate incompatibility. However, since `Finding` and its children are not data class, I need to create `copyWithSeverity` to override the given severity.

Followup
===========
I did not deprecate or remove `Severity`, `maxIssues`, `warningsAsErrors` in this PR. If this is a good time to do so, I would be happy to do those in a follow-up PR.

Test
====
In addition to the unit test, I also performed an integration test in a different repo. Users can configure severity at ruleset level and rule level.
```
style:
  severity: error
  MagicNumber:
    severity: ignore
```

2020-12-20 05:59 UTC, chao2zhang commented
I also realized that the severity, for now, is only in XML + Sarif. We are not differentiating severities in HTML or console output. If this is a good idea, please react to this comment so I will open a new issue for supporting them.

1. For txt, the output should include the severity level. 
2. For console, we should color-code each finding in addition to showing the severity.
3. For HTML, we should both display the severity and use a different background.

2020-12-20 09:21 UTC, BraisGabin commented
I agree with all except html. I don't think that we should change all the background. We could use a label and only change that label color.

2020-12-20 17:28 UTC, schalkms approved these changes
Looks good!
Anyhow, a refactoring would be great in separate PR in order to implement the severity levels properly and keep the architecture tidy. Then there's no need for copying stuff around and no risk to introduce cyclic dependencies with future refactorings.

> We can break such cycling dependency by refactoring, but I would prefer doing so in the next PR where we can remove the existing Severity and replace it with the new SeverityLevel.

2020-12-20 17:30 UTC, schalkms commented
> If this is a good idea, please react to this comment so I will open a new issue for supporting them.
> 1. For txt, the output should include the severity level.
> 2. For console, we should color-code each finding in addition to showing the severity.
> 3. For HTML, we should both display the severity and use a different background.

+1 great
I agree with this suggestion. I wouldn't want to build it overly complicated, so simplicity is the key here.

2020-12-20 18:04 UTC, chao2zhang commented
> Looks good!
> Anyhow, a refactoring would be great in separate PR in order to implement the severity levels properly and keep the architecture tidy. Then there's no need for copying stuff around and no risk to introduce cyclic dependencies with future refactorings.
> 
> > We can break such cycling dependency by refactoring, but I would prefer doing so in the next PR where we can remove the existing Severity and replace it with the new SeverityLevel.

#3127 prototyped a new Rule API, which is much cleaner, but also not backward compatible. In order to keep the severity within every `Issue`, it will be a breaking change and I would prefer to wait till Detekt 2.0 for making such changes.

I have seen Detekt 2.0 mentioned in a few issues. Do we know when and how we are planning this? I imagine there will be a separate 2.0 branch where we can merge all breaking changes.

2020-12-20 18:35 UTC, schalkms commented
> #3127 prototyped a new Rule API, which is much cleaner, but also not backward compatible. In order to keep the severity within every Issue, it will be a breaking change and I would prefer to wait till Detekt 2.0 for making such changes.
>
> I have seen Detekt 2.0 mentioned in a few issues. Do we know when and how we are planning this? I imagine there will be a separate 2.0 branch where we can merge all breaking changes.

At the moment those PRs are tagged in the **milestone** field with the corresponding detekt version.
Nevertheless, with the number of those PRs growing I suggest to create a new v2.0 branch for simplicity reasons.

2020-12-20 20:29 UTC, BraisGabin commented
We talk a lot about 2.0 but we don't have the list of things that we want to change. So I'm not sure about creating a new branch. #3127 pretends to be retrocompatible. I mean, the idea is to deprecate the old api and keep it until 2.0.

2020-12-21 16:46 UTC, arturbosch requested changes
Implementation looks good!
I think this could be backwards compatible for 1.x, please see my two comments

2020-12-21 16:46 UTC, arturbosch commented on detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/Rule.kt
> +        return enumValueOf(configValue.toUpperCase())
All `Finding` implementation use `Warning` as default which should be backwards compatible (checkstyle format is consumed by jenkins warnings plugin). Defaulting to error here may break CI for users of the jenkins plugin.

2020-12-21 16:46 UTC, arturbosch commented on detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/Findings.kt
> +    fun copyWithSeverity(severity: SeverityLevel): Finding
Having a default implementation which returns self would make this backwards compatible with 1.x?

2020-12-21 17:04 UTC, chao2zhang commented on detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/Findings.kt
> +    fun copyWithSeverity(severity: SeverityLevel): Finding
Good point

2020-12-21 17:06 UTC, chao2zhang commented on detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/Rule.kt
> +        return enumValueOf(configValue.toUpperCase())
Great catch. I updated the default severity in `TestFactory.createFinding()` but forgot to update it here.

2020-12-21 17:17 UTC, arturbosch approved these changes

2020-12-21 18:45 UTC, BraisGabin reviewed
Great PR! I'm just a bit concerned about the compatibility.

2020-12-21 18:45 UTC, BraisGabin commented on detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/CodeSmell.kt
> +    severity: SeverityLevel = SeverityLevel.WARNING
I do little about code compatibility, but this will break binary compatibility, right? I mean, we are going to force to all our users to recompile their plugins and upload a new version.

If we want to fix it I think that we should create a secundary constructor that have exactly the same signature as the previous one. The binary compatibility in Kotlin is messy... Maybe we could definde some number of minor release where we provide binary compatibility. This way we could deprecate this secundary constructor and give it a version or time when it will be removed. We can even create a custom rule to check this.

2020-12-21 18:56 UTC, arturbosch commented on detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/CodeSmell.kt
> +    severity: SeverityLevel = SeverityLevel.WARNING
Good catch! We also used a secondary constructor for `Entity` and co.

2020-12-21 19:02 UTC, chao2zhang commented on detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/CodeSmell.kt
> +    severity: SeverityLevel = SeverityLevel.WARNING
- Adding a default argument maintains the source compatibility, but breaks the binary compatibility
  [Maintaining compatibility in Kotlin libraries](https://zsmb.co/maintaining-compatibility-in-kotlin-libraries/)
- We could use [Kotlin binary compatibility](https://github.com/Kotlin/binary-compatibility-validator) to validate API breaking changes.
- We could also enable [explicit API mode](https://kotlinlang.org/docs/reference/whatsnew14.html#explicit-api-mode-for-library-authors) to make sure we are not accidentally exposing API.
- In this particular case, let me fix as you suggested.

2020-12-21 19:11 UTC, BraisGabin commented on detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/CodeSmell.kt
> +    severity: SeverityLevel = SeverityLevel.WARNING
@chao2zhang, could you add your ideas in #3315? I just created it so we can automatice this. It is impossible to catch these breaking changes just by eye.

2020-12-21 19:16 UTC, BraisGabin commented on detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/CodeSmell.kt
> +    constructor(
```suggestion
    @Deprecated("This constructor is provided for binary compatibility, use the primary constructor instead")
    constructor(
```

2020-12-21 19:16 UTC, BraisGabin commented on detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/CodeSmell.kt
> +    severity: SeverityLevel = SeverityLevel.WARNING
Do we want a default value now that we don't need it for source compatibility?

2020-12-21 19:25 UTC, chao2zhang commented on detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/CodeSmell.kt
> +    severity: SeverityLevel = SeverityLevel.WARNING
The concern here is that I do not expect rule authors to override the severity here.

Here is another idea: Rather than exposing `Finding.copyWithSeverity()` in the interface, we could create the severity as a `var` with `internal set()`, this way only `Rule` is able to mutate it and we further minimize the exposed APIs.

2020-12-21 19:54 UTC, chao2zhang commented on detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/CodeSmell.kt
> +    severity: SeverityLevel = SeverityLevel.WARNING
Check out the new diff I published.

2020-12-21 20:18 UTC, BraisGabin approved these changes

2020-12-27 02:38 UTC, chao2zhang commented
This PR also depends on #3320

2020-12-27 12:09 UTC, BraisGabin commented on detekt-report-sarif/src/test/kotlin/io/github/detekt/report/sarif/SarifOutputReportSpec.kt
> +                createFinding(ruleName = "TestSmellD", severity = SeverityLevel.IGNORE)
🤔 does this have sense? Should we ever have an issue with ignore severity? I mean, to our users we provide the option to set severity as ignore. But, inside the core should we have that severity? Shouldn't we map that severity as `active = false` and don't even have it as a valid value in `SeverityLevel`?

2020-12-27 16:08 UTC, schalkms commented on detekt-report-sarif/src/test/kotlin/io/github/detekt/report/sarif/SarifOutputReportSpec.kt
> +                createFinding(ruleName = "TestSmellD", severity = SeverityLevel.IGNORE)
Good idea 💡

2020-12-27 17:09 UTC, chao2zhang commented on detekt-report-sarif/src/test/kotlin/io/github/detekt/report/sarif/SarifOutputReportSpec.kt
> +                createFinding(ruleName = "TestSmellD", severity = SeverityLevel.IGNORE)
It is a good question.  When breaking change is allowed, I meant to see if we should all migrate `active = false` to `severity = ignore`.

We can postpone that discussion later and I will remove SeverityLevel.IGNORE in this PR to not incur confusion.

2020-12-27 17:38 UTC, schalkms commented on detekt-report-sarif/src/test/kotlin/io/github/detekt/report/sarif/SarifOutputReportSpec.kt
> +                createFinding(ruleName = "TestSmellD", severity = SeverityLevel.IGNORE)
> We can postpone that discussion later and I will remove SeverityLevel.IGNORE in this PR to not incur confusion.

+1

2020-12-27 18:44 UTC, BraisGabin commented on detekt-report-sarif/src/test/kotlin/io/github/detekt/report/sarif/SarifOutputReportSpec.kt
> +                createFinding(ruleName = "TestSmellD", severity = SeverityLevel.IGNORE)
Do we need to pospone it? I mean, right now we can make that `Rule.active` is the same as `yml.active && yml.severity != "ignore"`. And we can remove `SeverityLevel.IGNORE` as a value of the enum.

2020-12-27 21:24 UTC, chao2zhang commented on detekt-report-sarif/src/test/kotlin/io/github/detekt/report/sarif/SarifOutputReportSpec.kt
> +                createFinding(ruleName = "TestSmellD", severity = SeverityLevel.IGNORE)
I think about determining `severity == "ignore"` when calculating active, but the more I think, the more edge cases we could introduce. There can be a combination of cases:
- `active` is false, and `severity` is not set either => We should not run the rule
- `active` is false, but `severity` is set => We should not run the rule, but should we raise an error?
- `active` is true, and `severity` is not set => We should run the rule, with default level = warning
- `active` is true, and `severity` is set => We should run the rule, unless the default level is ignore?

Now in the future for Detekt 2.0, I would prefer using one config key to configure the severity and enabled state. Having two causes more confusion in my opinion.

2020-12-27 22:00 UTC, BraisGabin commented on detekt-report-sarif/src/test/kotlin/io/github/detekt/report/sarif/SarifOutputReportSpec.kt
> +                createFinding(ruleName = "TestSmellD", severity = SeverityLevel.IGNORE)
I agree, we should remove `active` from the config file in 2.0.

2021-01-04 19:20 UTC, merged