Switch order of correctable rules and other rules
detekt/detekt pull request #3317
Opened 2020-12-24 01:14 UTC by chao2zhang

Interestingly, the previous code caused a crash in (#2693). The problem is that we run Ktlint/CommentSpacing before running LongMethod. Because CommentSpacing mutates the `ktfile.text`, but does not update
`Ktfile.viewerProvider.document`, resulting in an inconsistent state and eventually crash (https://github.com/detekt/detekt/issues/2693#issuecomment-750395108)

Note that this commit is merely a short-term fix. In the long term, we should be more careful in rule running order, while leveraging parallelism to optimize the runtime.

Test
====
I verified that the correct violations `CommentSpacing` are reported in the sample project (https://github.com/andrey-bolduzev/detekt_issue_2693) after the change. Before this change, it will crash with `java.lang.IndexOutOfBoundsException: Wrong offset: 834. Should be in range: [0, 833]`

2020-12-24 01:19 UTC, chao2zhang commented
Fun fact: I almost spent my day debugging this. I initially thought this is a Kotlin compiler bug and started by refactoring the code to extract `PsiWhitespace`, then scratched my head on why `PsiWhitespace` is by default not provided in the parsed `KtFile`. Luckily I was able to debug through the stack and find the root cause.

2020-12-24 08:37 UTC, BraisGabin commented
We can't merge this because it will break the html report and the position of a lot of issues. If you first run the no correctable and then the correctable ones all the issues that you found before could have change its position.

We need to find other way to fix this.

If I understand it correctly this error happens because some ktlint rules uses a value that doesn't update after change the KtFile, right? Could we create a PR (or open an issue first) to them?

2020-12-24 08:38 UTC, BraisGabin requested changes
We can't merge this because it will break the html report and the position of a lot of issues. If you first run the no correctable and then the correctable ones all the issues that you found before could have change its position.

We need to find other way to fix this.

If I understand it correctly this error happens because some ktlint rules uses a value that doesn't update after change the KtFile, right? Could we create a PR (or open an issue first) to them?

2020-12-24 17:07 UTC, chao2zhang commented
That's a good point. Let me summarize the dilemma:
- Run non-correctable rules before running correctable ones: The position reported in the non-correctable rules may be outdated when correctable ones were mutating the `KtFile` content
- Run correctable rules before running non-correctable ones: Ktlint rules mutates the ASTNode directly. Therefore there can be stale references that were not updated. In our case, `LinesOfCode` depends on `DiagnosticUtils.getLineAndColumnInPsiFile`, which internally uses the class `Document` to find line and column in the original value before correction. In fact `DiagnosticUtils` is eventually invoked by many of our rules.

There are several ways to fix them:
1. Keep with option 1 - If the `KtFile` content is mutated, we announce that locations might be offsetted.
2. Keep with option 1 - Find a smart way to handle `ASTNode` modification.
3. Keep with option 2 - Find a smart way to update all the stale references: Although this effort might be difficult to be exhaustive, and we need to keep maintaining them when we upgrade kotlin versions.
4. Keep with option 2 - Find a smart way to refactor off methods using the stale references.

There is a collection of tangential issues related to this:
a. KtlintMultiRule is regarded as either all auto-correctible or non-autocorrectible. But in fact, it mixes auto-correctible with non-autocorrectible rules. Thus we need to split KtlintMultiRule into two sets, at least.
b. KtLint rules have certain modifiers to impose orders as `MaxLineLengthRule` runs as the `Last` rule. Some long lines may not actually exceed the line length limit after mutation from other rules. I am pretty confident that this issue exists for Detekt as well.
c. Parallelism is my perception of the intention of creating `MultiRule`, but I believe we could do much better here to figure out the strategy across the board. The argument here would be a `Rule` can report `Multiple` issues.

Overall autocorrection is a difficult problem. I am wondering if Ktlint owners can shed some lights (The ordering marker interface was added in https://github.com/pinterest/ktlint/issues/101 and modified in https://github.com/pinterest/ktlint/issues/158)

2020-12-24 20:01 UTC, BraisGabin commented
Other option is to run the correctable ones first and, if there is any change, regenerate the KtFile. This one would be slower.

2020-12-26 16:45 UTC, chao2zhang commented
I may not have the privilege, but is it possible to convert this PR to a discussion? If not, let's create a new discussion and close this PR

2020-12-26 17:42 UTC, BraisGabin commented
> I may not have the privilege, but is it possible to convert this PR to a discussion? If not, let's create a new discussion and close this PR

It seems that we can't convert PRs in conversations. But I think that this is better suited in an issue. This is a bug.

2020-12-26 17:42 UTC, closed without merging