Add tests for UnnecessaryFilter rule
detekt/detekt pull request #3341
Opened 2021-01-01 21:41 UTC by VovaStelmashchuk

Issue: https://github.com/detekt/detekt/issues/3340

2021-01-01 21:42 UTC, VovaStelmashchuk commented
I don't have idea about implementation at the moment.

2021-01-01 22:41 UTC, BraisGabin commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryFilterSpec.kt
> +            assertThat(findings).isEmpty()
Shouldn't this report one issue? This could be replaced by `none { it > 2 }`

2021-01-01 23:24 UTC, VovaStelmashchuk commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryFilterSpec.kt
> +            assertThat(findings).isEmpty()
Fixed.

2021-01-10 15:19 UTC, cortinico commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryFilter.kt
> + *      .none { it > 1 }
Please add a `@requiresTypeResolution` here

2021-01-25 20:52 UTC, VovaStelmashchuk commented
Implementation ready. Can someone review my changes?

2021-01-25 23:06 UTC, chao2zhang commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryFilter.kt
> + *      .none { it > 1 }
@cortinico maybe I missed something, but why do we need a `@requiresTypeResolution`?

2021-01-26 12:12 UTC, VovaStelmashchuk commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryFilter.kt
> + *      .none { it > 1 }
https://detekt.github.io/detekt/type-resolution.html#is-my-rule-using-type-resolution
I agree with @chao2zhang According to this doc we don't need this annotation. I will remove this.

2021-01-26 17:01 UTC, chao2zhang commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryFilter.kt
> +        "UnnecessaryFilter",
```suggestion
        "filter() with other collection operations may be simplified.",
```

2021-01-26 17:01 UTC, chao2zhang approved these changes

2021-01-26 21:06 UTC, schalkms requested changes

2021-01-26 21:06 UTC, schalkms commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryFilter.kt
> +            "isNotEmpty", "none")
This will yield false-positives, if you have property accessors like this. It's not checked, whether the calling function is actually a high order function named `filter` with a lambda expression in it.

```
call().filter.size
```

```suggestion
        expression.checkNextLeaf("isEmpty", "any")
        expression.checkNextLeaf("isNotEmpty", "none")
```

2021-01-26 22:12 UTC, cortinico commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryFilter.kt
> + * Unnecessary filter add complexity to the code and accomplish noting. They should be removed.
```suggestion
 * Unnecessary filters add complexity to the code and accomplish noting. They should be removed.
```

2021-01-26 22:12 UTC, cortinico commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryFilter.kt
> +            "isNotEmpty", "none")
> whether the calling function is actually a high order function named filter

nit: To be 100% exact we should also verify that the calling method is the "filter" from the Kotlin stdlib (but that will require type resolution)

2021-01-26 22:12 UTC, cortinico commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryFilter.kt
> +                "$this can be replace by $correctOperator { ${this.lambda()?.text}}"))
```suggestion
                "$this can be replaced by $correctOperator { ${this.lambda()?.text}}"))
```

2021-01-26 22:12 UTC, cortinico commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryFilter.kt
> +    }
I'm unsure about this. While is a nice to have, it's used only for "suggestion" and it exposes  us to further breakage in the future shall the API be changed on the Kotlin side.

I believe we should either remove it, or if we wish to keep it I'd like to ask you to asset the report message in your tests.

2021-01-26 23:30 UTC, chao2zhang commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryFilter.kt
> +            "isNotEmpty", "none")
Ah that's why you were suggesting adding requiresTypeResolution in the first place.

2021-01-27 07:47 UTC, VovaStelmashchuk commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryFilter.kt
> +    }
Test added.

2021-01-27 08:05 UTC, VovaStelmashchuk commented
I see codecov report. I can add some test for increase test coverage. But i cannot see reason for add test only for increase test coverage. The additional test will not add real benefits.

2021-01-27 18:23 UTC, cortinico approved these changes

2021-01-27 18:26 UTC, cortinico commented
> I see codecov report. I can add some test for increase test coverage. But i cannot see reason for add test only for increase test coverage. The additional test will not add real benefits.

You're fine like that 👍 Codecov coverage report is not a hard requirement for merging. In this case you're at 76.00% of your patch that is totally fine

2021-01-27 18:51 UTC, schalkms commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryFilter.kt
> + * Unnecessary filters add complexity to the code and accomplish noting. They should be removed.
```suggestion
 * Unnecessary filters add complexity to the code and accomplish nothing. They should be removed.
```

2021-01-27 18:51 UTC, schalkms commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryFilter.kt
> +        expression.checkNextLeaf("isNotEmpty", "none")
Those calls could also be checked by: `resultingDescriptor.fqNameOrNull()`

2021-01-28 17:27 UTC, chao2zhang approved these changes

2021-01-28 17:27 UTC, chao2zhang commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryFilter.kt
> +                "${this.text} can be replaced by ${correctOperator ?: shortName} ${this.lambda()?.text}"
```suggestion
                "'${this.text}' can be replaced by '${correctOperator ?: shortName} ${this.lambda()?.text}'"
```

2021-01-28 17:27 UTC, chao2zhang commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryFilterSpec.kt
> +            assertThat(findings[0]).hasMessage("filter { it > 1 } can be replaced by size { it > 1 }")
```suggestion
            assertThat(findings[0]).hasMessage("'filter { it > 1 }' can be replaced by 'size { it > 1 }'")
```

2021-01-28 17:28 UTC, chao2zhang commented
Thank you so much for the contribution and for being patient in the back-and-forth requested changes.

2021-01-29 18:30 UTC, chao2zhang commented
For other maintainers in this PR (@cortinico @BraisGabin @schalkms): We entered 1.16-RC but is it reasonable to add new rules with active = false by default?
I can think of arguments for both sides:
- We want to only allow bug fixes in RC to speed up the full release
- We want people to try out experimental new rules early so we can enable them by default faster

2021-01-29 19:26 UTC, cortinico commented
> * We want to only allow bug fixes in RC to speed up the full release
> * We want people to try out experimental new rules early so we can enable them by default faster

Historically we've been pretty slow at enabling rules by default so I don't mind adding a disabled rule in a RC. Also if we have rules that are ready to go, like this one or #3413, I'll try to squeeze them into `1.16.0` to let them reach our users sooner (so we can get a faster feedback loop).

That being said, I'm in for merging this

2021-01-29 21:32 UTC, BraisGabin commented
:shipit:! The RC are more to make sure that some changes in the core or clients doesn't break. We did add rules between RC previusly.

2021-01-29 21:45 UTC, merged