Drop support to Gradle 5
detekt/detekt pull request #3647
Opened 2021-04-02 20:42 UTC by BraisGabin

Drop support to gradle 5.

5.0 was release at [16/Apr/2019](https://gradle.org/releases/). This moves the support 6.0. It was release at [08/Nov/2019](https://gradle.org/releases/). Maybe we coud be even more aggresive here but I think that 6.0 is a safe commitment.

As a reference the Gradle Android Plugin set the [minimum gradle version to 6.1 at April 2020]( https://developer.android.com/studio/releases/gradle-plugin#4-0-0). And the last version of the AGP requires Gradle 6.5

2021-04-03 05:41 UTC, chao2zhang approved these changes

2021-04-03 13:12 UTC, 3flex requested changes
Kotlin's current minimum supported Gradle version is 5.4. Why not keep the versions aligned? Increasing the minimum now seems arbitrary.

That said, I believe Kotlin 1.5 will bump the minimum supported version to 6.1 so when that's released and detekt updates to 1.5 I'd support an update to 6.1.

2021-04-03 13:26 UTC, BraisGabin commented
Good reason! Yes, let's keep us aligned with the Kotlin Gradle Plugin.

2021-04-03 13:26 UTC, closed without merging

2021-05-22 10:32 UTC, BraisGabin commented
> That said, I believe Kotlin 1.5 will bump the minimum supported version to 6.1 so when that's released and detekt updates to 1.5 I'd support an update to 6.1.

I can not find anywhere about this bump of the minimum version. Do this happen?

2021-05-23 00:20 UTC, 3flex commented
It did: https://kotlinlang.org/docs/gradle.html#plugin-and-versions