Use @Configuration for rules-errorprone
detekt/detekt pull request #3772
Opened 2021-05-13 05:22 UTC by chao2zhang

This belongs to #3670 and replaces all configuration kdoc tags in detekt-rules-errorprone with annotation.

2021-05-13 08:43 UTC, cortinico approved these changes

2021-05-13 10:46 UTC, marschwar requested changes
Please complete the description for `LateInitUsage#excludeAnnotatedProperties` and convert the configuration in `ImplicitUnitReturnType`

2021-05-13 12:23 UTC, marschwar commented on detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/LateinitUsage.kt
> +        list.map { it.removePrefix("*").removeSuffix("*") }
I just realized that this actually works differently. I will need to go back and use `it.removePrefix("*").removeSuffix("*")`

2021-05-13 14:04 UTC, chao2zhang commented on detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/LateinitUsage.kt
> +    @Configuration("Allows you to provide a list of annotations that disable")
Good catch

2021-05-13 14:04 UTC, chao2zhang commented
> convert the configuration in `ImplicitUnitReturnType`

Ooops, the @configuration appears above the <noncompliant>

2021-05-13 14:18 UTC, chao2zhang commented on detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/LateinitUsage.kt
> +        list.map { it.removePrefix("*").removeSuffix("*") }
Indeed, fortunately we have test coverage that helps me verify this.

2021-05-13 16:35 UTC, marschwar approved these changes

2021-05-13 17:26 UTC, marschwar requested changes

2021-05-13 17:26 UTC, marschwar commented on detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/LateinitUsage.kt
> +    private val ignoreOnClassesPattern: Regex by config("''", String::toRegex)
This needs to be `""` instead of `"''"`.

2021-05-13 17:26 UTC, marschwar commented on detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt
> - * @configuration returnValueAnnotations - List of glob patterns to be used as inspection annotation (default: `['*.CheckReturnValue', '*.CheckResult']`)
The order of the fields is flipped which leads to a change in the generated default-detekt-config.yml. I think the order should be changed or the changed default-detekt-config.yml should be part of this pr.

2021-05-13 20:35 UTC, schalkms approved these changes

2021-05-15 22:49 UTC, chao2zhang commented on detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/IgnoredReturnValue.kt
> - * @configuration returnValueAnnotations - List of glob patterns to be used as inspection annotation (default: `['*.CheckReturnValue', '*.CheckResult']`)
Good catch

2021-05-16 10:33 UTC, marschwar approved these changes

2021-05-16 18:47 UTC, BraisGabin approved these changes

2021-05-16 21:42 UTC, merged