Add new rule: BooleanPropertyPrefixedWithAllowedWords
detekt/detekt pull request #3795
Opened 2021-05-18 21:27 UTC by AlinaRakhimova

I added a new rule to check the naming of boolean variables to improve the readability of the code.

For example, 

`val enabled = true`

Instead of should prefer to 

`val isEnabled = true`

2021-05-19 18:30 UTC, schalkms reviewed
Hello Alina,
I don't know if you are aware of it, but there exists already a rule, which works essentially the same as your rule. The controversial rule is called `NonBooleanPropertyPrefixedWithIs`. Hence, detekt disables this rule by default.

I don't think detekt needs a second rule even if minor differences exist. Therefore, I have to unfortunately declare this as *won't merge*. Still, you can use this rule in a custom rule set as you like. See [here](https://detekt.github.io/detekt/extensions.html#custom-rulesets) for more details.

https://github.com/detekt/detekt/blob/main/detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/NonBooleanPropertyPrefixedWithIs.kt

2021-05-20 06:30 UTC, shumidub commented
But, this is different rules. NonBooleanPropertyPrefixedWithIs - for NOT boolean property and don't check boolean properties naming.

BooleanPropertyPrefixedWithAllowedWords - for booleans.

2021-05-20 11:14 UTC, cortinico commented
Thanks for taking the time to add a new rule 🙏

I believe we could consider this rule, but it falls a bit in the `controversial` area. 
Specifically I don't agree that:

```
val enabled = true
```
is less readable than:
```
val isEnabled = true
```
but that's debatable, so I can understand how developers might want to enforce some prefixes on their `Boolean` property.

I would like to get other maintainers opinion on this. 

Some things that needs to be addressed/discussed:
- The rule name should probably be tweaked. Ideally `BooleanPropertyPrefix` or `BooleanPropertyNaming`.
- We already have a similar rule that does this, is `VariableNaming`. Your rule is basically doing the same behavior but just for `Boolean` property. I'm unsure if this should be a separate rule or we should extend `VariableNaming` (that will impose type resolution on this rule, making it a "mixed rule" that we try to avoid #2994).
- Do we have some reference from the official Kotlin guidelines where the boolean variable naming is suggested? If so, that should be linked in the documentation.

2021-05-20 11:20 UTC, cortinico commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyPrefixedWithAllowedWords.kt
> + * @requiresTypeResolution
You should use the `@RequiresTypeResolution` annotation instead.

2021-05-20 11:20 UTC, cortinico commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyPrefixedWithAllowedWords.kt
> + *
`<compliant>` and `<noncompliant>` examples are missing

2021-05-20 11:20 UTC, cortinico commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyPrefixedWithAllowedWords.kt
> +        if (property.isConstant()) return
Why are you skipping constants?

2021-05-20 11:20 UTC, cortinico commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyPrefixedWithAllowedWords.kt
> +        if (name in listOf(VALUE_CONDITION, VALUE_PREDICATE, VALUE_IT, UNUSED_PARAM_NAME)) {
Why are you filtering for `condition` and `predicate`?

2021-05-20 11:20 UTC, cortinico commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyPrefixedWithAllowedWords.kt
> +    private val regex = Regex("^(is|has|should|need|noNeed|was|are|may|can|had|for|with)")
The list of prefixes should be configurable

2021-05-20 11:20 UTC, cortinico commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyPrefixedWithAllowedWords.kt
> +            ?.getJetTypeFqName(false)
You should not use `getJetTypeFqName` but `fqNameOrNull`: https://github.com/detekt/detekt/pull/3613

2021-05-20 11:20 UTC, cortinico commented on detekt-rules-naming/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyPrefixedWithAllowedWordsSpec.kt
> +    describe("IsPropertyNaming rule") {
```suggestion
    describe("BooleanPropertyPrefixedWithAllowedWords rule") {
```

2021-05-20 11:20 UTC, cortinico commented on detekt-rules-naming/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyPrefixedWithAllowedWordsSpec.kt
> +                val code = """data class O (var default: Boolean)"""
`O` is an unlucky char for a class name. It's hard to read if it's a capital O or a zero 0. Maybe change with `Data` or whatever class name you prefer :)

2021-05-20 20:12 UTC, schalkms commented
> I believe we could consider this rule, but it falls a bit in the controversial area

The question is whether more controversial rules shall exist in detekt considering the increasing maintenance effort in this project.

> We already have a similar rule that does this, is VariableNaming. Your rule is basically doing the same behavior but just for Boolean property. I'm unsure if this should be a separate rule or we should extend VariableNaming (that will impose type resolution on this rule, making it a "mixed rule" that we try to avoid #2994).

I agree with this and forgot to also reference the `VariableNaming` rule.

> Do we have some reference from the official Kotlin guidelines where the boolean variable naming is suggested? If so, that should be linked in the documentation.

I don't think there exists one. This constitutes more of a common rule in many projects.

2021-05-21 07:05 UTC, AlinaRakhimova commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyPrefixedWithAllowedWords.kt
> +        if (name in listOf(VALUE_CONDITION, VALUE_PREDICATE, VALUE_IT, UNUSED_PARAM_NAME)) {
I think we can give the ability to name the parameters "condition" and "predicate". For example, it can be useful for creating common extension functions with a boolean parameter.

2021-05-21 07:07 UTC, AlinaRakhimova commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyPrefixedWithAllowedWords.kt
> +        if (property.isConstant()) return
I thought constants could use their own naming conventions. Do you think I should remove this condition?

2021-05-21 08:18 UTC, cortinico commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyPrefixedWithAllowedWords.kt
> +        if (name in listOf(VALUE_CONDITION, VALUE_PREDICATE, VALUE_IT, UNUSED_PARAM_NAME)) {
I believe there should not be any hardcoded "exception", to follow the least astonishment principle (https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

Why "condition" and "predicate" should be an exception, and other synonym should not (e.g. "criteria", "rule", "guard", "expression", ...)

2021-05-21 08:19 UTC, cortinico commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyPrefixedWithAllowedWords.kt
> +        if (property.isConstant()) return
> Do you think I should remove this condition?

Not necessarily :) I'm just challenging some of the rule assumptions to understand the use cases.

> I thought constants could use their own naming conventions.

Why this? Do you have some examples?

2021-05-21 09:30 UTC, AlinaRakhimova commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyPrefixedWithAllowedWords.kt
> +        if (name in listOf(VALUE_CONDITION, VALUE_PREDICATE, VALUE_IT, UNUSED_PARAM_NAME)) {
You're right.
Then I'll make the list of prefixes configurable and remove all of these conditions. The user will be able to customize the rule through the configuration

2021-05-21 10:02 UTC, AlinaRakhimova commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyPrefixedWithAllowedWords.kt
> +        if (property.isConstant()) return
Actually, I have no real examples. It seems to me that logical constants are rarely used. Then I will remove this condition.

2021-05-24 21:47 UTC, BraisGabin commented
> Do we have some reference from the official Kotlin guidelines where the boolean variable naming is suggested? If so, that should be linked in the documentation.

I would not add this rule if there is not a source or reference to back it. I think that, as detekt, we should not be that opinated. #3150 was closed even with references. I understand the rule and maybe I would use it in my project too, but I don't think we should have it in our default rulesets.

2021-05-25 06:29 UTC, AlinaRakhimova commented
If the user does not want to use this rule, he will not enable it in the config file

2021-05-25 06:29 UTC, AlinaRakhimova commented
> > Do we have some reference from the official Kotlin guidelines where the boolean variable naming is suggested? If so, that should be linked in the documentation.
> 
> I would not add this rule if there is not a source or reference to back it. I think that, as detekt, we should not be that opinated. #3150 was closed even with references. I understand the rule and maybe I would use it in my project too, but I don't think we should have it in our default rulesets.

If the user does not want to use this rule, he will not enable it in the config file

2021-05-28 05:26 UTC, shumidub commented
The rule is very useful, it improves the readability and clarity of the code. It will be great if it will be available as an optional rule.

2021-05-28 21:31 UTC, chao2zhang commented
With regards to references:
1. Java Bean requires boolean property to be prefixed with `is` (https://www.oracle.com/java/technologies/javase/javabeans-spec.html)
In addition, for boolean properties, we allow a getter method to match the pattern:
`public boolean is<PropertyName>();`
This “is<PropertyName>” method may be provided instead of a “get<PropertyName>” method, or it may be provided in addition to a “get<PropertyName>” method.
In either case, if the “is<PropertyName>” method is present for a boolean property then we will
use the “is<PropertyName>” method to read the property value.
An example boolean property might be:
```
   public boolean isMarsupial();
   public void setMarsupial(boolean m);
```

2. Kotlin-Java interop (https://kotlinlang.org/docs/java-interop.html#getters-and-setters)
Boolean accessor methods (where the name of the getter starts with is and the name of the setter starts with set) are represented as properties which have the same name as the getter method.

3. Android lint implemented checks requiring specific bean style for Java methods `Accessor methods require a ‘get’ prefix or for boolean-returning methods an ‘is’ prefix can be used.`
https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-master-dev:lint/libs/lint-checks/src/main/java/com/android/tools/lint/checks/InteroperabilityDetector.kt;l=141?q=Interoperability%20lint

The above references apply to Java code, yet we do not have a Kotlin coding convention encouraging or discouraging the naming pattern for a boolean property. My vote would be yes as this rule is rather easy to maintain and we could document these references in the KDoc so that we keep this rule disabled in the future.

2021-06-06 20:33 UTC, chao2zhang commented
Other thoughts? We probably want to reach a consensus on this PR before the next release.

2021-06-07 11:16 UTC, cortinico approved these changes
I believe we could add this rule and have it disabled 👍 It's not as controversial as other and the maintenance cost is not as high.

2021-06-07 11:16 UTC, cortinico commented on detekt-core/src/main/resources/default-detekt-config.yml
> +    allowedPrefixes: '^(is|has|should|need|noNeed|was|are|may|can|had|for|with)'
```suggestion
    allowedPrefixes: '^(is|has|are)'
```

I believe the default value is a bit too long? 🤔 Or at least is really opinionated. I would opt for a shorter list if possible.

2021-06-07 16:07 UTC, shumidub commented on detekt-core/src/main/resources/default-detekt-config.yml
> +    allowedPrefixes: '^(is|has|should|need|noNeed|was|are|may|can|had|for|with)'
maybe  '^(is|has|are|should)' ? 🤔

but the current long list is not bad either

2021-06-07 16:51 UTC, marschwar commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyNaming.kt
> + * * <noncompliant>
```suggestion
 * <noncompliant>
```

2021-06-07 16:55 UTC, marschwar commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyNaming.kt
> + * @configuration allowedPrefixes - naming pattern (default: `'^(is|has|should|need|noNeed|was|are|may|can|had|for|with)'`)
Please remove the kdoc configuration in favour of the `@Configuration` annotation.  e.g.

```kotlin
@Configuration("Description of this configuration option")
private val allowedPrefixes: Regex by config("^(is|has)'", String::toRegex)
```

2021-06-07 16:59 UTC, marschwar commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyNaming.kt
> +    private val allowedPrefixes by LazyRegex(
This should either be called `allowedPattern` (or something similar or it should be a list of Strings
```kotlin 
@Configuration("Description of this configuration option")
private val allowedPattern: Regex by config("^(is|has)'", String::toRegex)
// or
@Configuration("Description of this configuration option")
private val allowedPrefixes: List<String> by config(listOf("is", "has"))
```

2021-06-07 18:25 UTC, marschwar commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/NamingRules.kt
> +    private val booleanPropertyNamingRule = BooleanPropertyNaming(config)
I could be wrong on this, but please double check if `visitParameter()` is ever called on your rule. Maybe someone else can suggest whether this rule should be part of the MutlRule or should be set up separately.

2021-06-07 18:26 UTC, marschwar commented on detekt-rules-naming/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyNamingSpec.kt
> +})
Maybe add an additional test case that checks if the configuration option is picked up correctly?

2021-06-14 11:26 UTC, shumidub approved these changes

2021-06-14 14:12 UTC, marschwar requested changes
Please use the annotation based rule configurations instead of kdoc.

2021-07-03 05:49 UTC, AlinaRakhimova commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/NamingRules.kt
> +    private val booleanPropertyNamingRule = BooleanPropertyNaming(config)
Hi!
`visitParameter()` is called on this rule
I added my rule to this class as well as `NonBooleanPropertyPrefixedWithIs`

2021-07-03 06:27 UTC, AlinaRakhimova commented on detekt-rules-naming/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyNamingSpec.kt
> +})
Test was added

2021-07-03 16:11 UTC, marschwar commented on detekt-core/src/main/resources/default-detekt-config.yml
> +    allowedPrefixes: '^(is|has|are)'
Please rerun `./gradlew :detekt-generator:generateDocumentation` for the renaming of the property to take effect.

2021-07-03 16:14 UTC, marschwar commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyNaming.kt
> +    )
```suggestion
    private val allowedPattern: Regex by config("^(is|has|are)", String::toRegex)
```
`LazyRegex` will be marked deprecated soon.

2021-07-03 16:21 UTC, marschwar commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyNaming.kt
> +    )
I think this confusing to the user. We should either allow users to specify regular expression patterns that match the entire boolean property or have a list of prefixes. Having a pattern that matches only parts of the name to me feels rather unusual.

2021-07-03 16:23 UTC, marschwar commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/BooleanPropertyNaming.kt
> + * is|has|are.
I think it is _"dangerous"_ to put the defaults into the rule description. This will eventually deviate from the truth.

2021-07-30 08:16 UTC, AlinaRakhimova commented
> Please use the annotation based rule configurations instead of kdoc.

I made it

2021-07-31 10:49 UTC, cortinico commented
Is there anything missing to merge this?

2021-07-31 10:52 UTC, AlinaRakhimova commented
> Is there anything missing to merge this?

Hi! All discussions were resolved

2021-07-31 10:55 UTC, cortinico commented
> Hi! All discussions were resolved

Can I ask you to address the CI failures?

2021-07-31 10:57 UTC, AlinaRakhimova commented
> > Hi! All discussions were resolved
> 
> Can I ask you to address the CI failures?

I'll try to do it

2021-08-01 21:03 UTC, marschwar commented
I think the code itself is fine (once it compiles again :smiley: - The config delegate was moved to a different package.). 

I have an issue with its inconsistent documentation. I know that it started out to focus on variable name prefixes, but when the rule was renamed to `BooleanPropertyNaming` all mentions of _"prefix"_ should have been removed from it as well. The users will not look at the code but rather its documentation so please be precise with what the rule does and how it can be configured.

Thank you for your contribution. I think it's really close. Sorry for the delay.

2021-08-05 22:06 UTC, marschwar approved these changes

2021-08-05 22:08 UTC, merged

2021-08-05 22:08 UTC, cortinico commented
Thanks for the contrib @AlinaRakhimova, sorry it took a bit longer than usual 🙏