Fix false positive in RethrowCaughtException for try with more than one catch (#4367)
detekt/detekt pull request #4369
Opened 2021-12-10 23:12 UTC by strkkk

Closes #4367 

1. Fixes false positive
2. One more test input is added (when same exception is thrown but with `this` qualifier)

2021-12-11 11:39 UTC, BraisGabin reviewed
👏 really good first contribution :) Thanks!

2021-12-11 11:39 UTC, BraisGabin commented on detekt-rules-exceptions/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/RethrowCaughtExceptionSpec.kt
> +            """
```kotlin
                fun f() {
                    try {
                    } catch (e: CancellationException) {
                        print(e)
                    } catch (e: Exception) {
                        throw e
                    }
                }
```

Do we have a test for this case? To ensure that we flag it?

2021-12-11 12:11 UTC, strkkk commented on detekt-rules-exceptions/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/RethrowCaughtExceptionSpec.kt
> +            """
I believe it is same thing, regardless order of catch blocks.

Anyway, I updated this input with reversed order (handling, than throwing)

2021-12-11 12:52 UTC, BraisGabin commented on detekt-rules-exceptions/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/RethrowCaughtExceptionSpec.kt
> +            """
No, the order matter here. In this case the second catch is completely useless. In the previous case it wasn't.

2021-12-11 13:54 UTC, strkkk commented on detekt-rules-exceptions/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/RethrowCaughtExceptionSpec.kt
> +            """
yes, you are right. Anyway, both cases produce no violations now. Can you start PR workflows? it needs mantainer rights to run

2021-12-15 20:06 UTC, BraisGabin commented on detekt-rules-exceptions/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/RethrowCaughtExceptionSpec.kt
> +            """
But the second one should be a violation. You are catching the exception just to rethrow it. You can remove that `catch`.

2021-12-17 14:38 UTC, cortinico approved these changes
LGTM 👍

2021-12-17 23:54 UTC, BraisGabin requested changes
Adding request for changes becuase right now it introduces a false-negative as commented in this thread: https://github.com/detekt/detekt/pull/4369/files#r767144893

2021-12-18 13:04 UTC, strkkk commented on detekt-rules-exceptions/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/RethrowCaughtExceptionSpec.kt
> +            """
@BraisGabin fixed

2021-12-21 12:09 UTC, BraisGabin approved these changes

2021-12-21 12:10 UTC, BraisGabin commented
Thank you so much! I'll merge it as soon as CI passes :). Greate job.

2021-12-21 13:11 UTC, BraisGabin commented
There is an issue in the code, could you check and fix it? https://github.com/detekt/detekt/runs/4594574549?check_suite_focus=true#step:4:356

2021-12-21 18:21 UTC, strkkk commented
@BraisGabin please trigger ci

2021-12-21 20:39 UTC, merged