Override vars will not be flagged if bindingContext is not set
detekt/detekt pull request #4477
Opened 2022-01-10 14:52 UTC by severn-everett

This addresses issue #4474

2022-01-10 16:45 UTC, BraisGabin approved these changes

2022-01-11 13:27 UTC, cortinico requested changes
I think we should ship this change as it is, but instead add a:

```
if(bindingContext == BindingContext.EMPTY) return`
```

statement inside the `visitKtFile` method on top of this class. The problem is that this rule is a rule annotated with `@RequiresTypeResolution`, but failing to add early return statement is allowing to run this rule without TR.

This is a bit of a bummer as this rule is now a mixed rule (see #2994) which I believe it should have never been (see https://github.com/detekt/detekt/pull/3880)

2022-01-13 22:45 UTC, BraisGabin commented
Cortinico is right, I was mistaken here.

We should just disable the rule and honor the annotation. Something like adding

```kotlin
if (bindingContext == BindingContext.EMPTY) return
```

should do the trick

2022-01-20 22:54 UTC, BraisGabin approved these changes

2022-01-28 01:36 UTC, cortinico approved these changes

2022-01-28 01:36 UTC, merged