Add Gradle Enterprise instructions for maintainers.
detekt/detekt pull request #4698
Opened 2022-04-08 21:57 UTC by cortinico

Adding some instructions on how to use Gradle Enterprise for our maintainers.

2022-04-08 21:57 UTC, cortinico commented
@3flex @marschwar @schalkms FYI ☝️

2022-04-08 22:20 UTC, chao2zhang approved these changes

2022-04-08 22:20 UTC, chao2zhang commented on .github/CONTRIBUTING.md
> +To do you mush:
```suggestion
You must follow the steps below:
```

2022-04-09 03:41 UTC, 3flex requested changes
Few typos to correct, looks good though, I will try this soon!

There might also need to be a process to verify ownership of a GitHub account when an email request comes in? I'm not on the Slack channel or anywhere else so other than trusting me when I email through it might be a bit tricky as my email isn't published publicly on GitHub.

This won't happen often though so it's not a major deal.

2022-04-09 03:41 UTC, 3flex commented on .github/CONTRIBUTING.md
> +to connect your local machine to the Gradle Enterprise instance, so you will also be publishign scans.
```suggestion
to connect your local machine to the Gradle Enterprise instance, so you will also be publishing scans.
```

2022-04-09 03:41 UTC, 3flex commented on .github/CONTRIBUTING.md
> +If you're a **maintaner** of a project under github.com/detekt/, you can request an access token
```suggestion
If you're a **maintainer** of a project under github.com/detekt/, you can request an access token
```

2022-04-09 03:41 UTC, 3flex commented on .github/CONTRIBUTING.md
> +1. Email us at [info@detekt.dev][7] or get in touch with one of the existing maintainer.
```suggestion
1. Email us at [info@detekt.dev][7] or get in touch with one of the existing maintainers.
```

2022-04-09 03:41 UTC, 3flex commented on .github/CONTRIBUTING.md
> +3. Run the `./gradlew provisionGradleEnterpriseAccessKey` tasks from the Detekt root folder
```suggestion
3. Run the `./gradlew provisionGradleEnterpriseAccessKey` task from the detekt root folder
```

2022-04-09 17:56 UTC, cortinico commented
> There might also need to be a process to verify ownership of a GitHub account when an email request comes in? I'm not on the Slack channel or anywhere else so other than trusting me when I email through it might be a bit tricky as my email isn't published publicly on GitHub.
> This won't happen often though so it's not a major deal.

True. We might ask people to create a repo inside github.com/detekt with a name like `verify-...` or something (similary to what sonatype does).

As you said also, this won't happen that frequently.

2022-04-09 21:16 UTC, 3flex approved these changes

2022-04-09 21:20 UTC, merged