Removed UnnecessaryAbstractClass if it inherits from a abstract class
detekt/detekt pull request #5009
Opened 2022-06-29 07:06 UTC by gouri-panda

closes: #4753 

Removed UnnecessaryAbstractClass if it inherits from abstract class an interface or that has concrete members.

2022-06-29 09:54 UTC, BraisGabin commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClassSpec.kt
> +                assertThat(subject.compileAndLintWithContext(env, code)).isEmpty()
This test shouldn't change, right?

2022-06-29 09:54 UTC, schalkms approved these changes
Thanks for the fix - appreciate it!

2022-06-29 09:54 UTC, schalkms commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClassSpec.kt
> +                    @Deprecated("We don't care about this first class")
I think this annotation can be removed.

```suggestion
```

2022-06-29 11:15 UTC, gouri-panda commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClassSpec.kt
> +                assertThat(subject.compileAndLintWithContext(env, code)).isEmpty()
@BraisGabin If we don't change it, the tests will fail.  I don't understand your question.

2022-06-29 12:27 UTC, gouri-panda commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClassSpec.kt
> +                    @Deprecated("We don't care about this first class")
@schalkms Without this, it fails.

2022-06-29 18:51 UTC, BraisGabin commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClassSpec.kt
> +                assertThat(subject.compileAndLintWithContext(env, code)).isEmpty()
But this one was right. An abstract class that only extends an interface is an unnecessary abstract class. The only one that should change is the case where an abstract class extend another abstract class because there you can't use an interface. (maybe I'm missing something here)

2022-06-30 09:59 UTC, gouri-panda commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClassSpec.kt
> +                assertThat(subject.compileAndLintWithContext(env, code)).isEmpty()
Should I revert that?

2022-06-30 10:32 UTC, BraisGabin commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClassSpec.kt
> +                assertThat(subject.compileAndLintWithContext(env, code)).isEmpty()
Yes. This test shouldn't change.

2022-07-02 17:57 UTC, amitdash291 commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClass.kt
> +            hasInheritedMember(true) -> return
The following enhancement to this logic will ensure the rule still fails for `interface` super types as mentioned in the earlier comment related to the `that inherits from an interface` test case.

```
hasInheritedMember(true) && !isParentInterface() -> return

private fun KtClass.isParentInterface() =
    (bindingContext[BindingContext.CLASS, this]?.unsubstitutedMemberScope as? LazyClassMemberScope)
        ?.supertypes?.firstOrNull()?.isInterface() == true
```

2022-07-03 09:32 UTC, gouri-panda commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClass.kt
> +            hasInheritedMember(true) -> return
@amitdash291 Thanks for advice and code :)

2022-07-03 19:18 UTC, BraisGabin commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClassSpec.kt
> +                """
I'm not sure, why is this raises a finding? Isn't this nearly the same case as the one before?

2022-07-03 19:30 UTC, gouri-panda commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClassSpec.kt
> +                """
Sure! I'll remove this.

2022-07-04 08:06 UTC, amitdash291 commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClass.kt
> +            hasInheritedMember(true) -> return
I think there's a corner case to test here. What if the class implements an interface and inherits from an Abstract class in that order. For eg may fail the rule whereas it's expected to pass:
```
interface I

abstract class A
// assume some fields for class A

abstract class B: I, A()
```

2022-07-04 17:11 UTC, amitdash291 requested changes
Refer reply to the code suggestion earlier.

2022-07-05 04:53 UTC, BraisGabin commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClass.kt
> +            hasInheritedMember(true) -> return
Is that even valid Kotlin code? Shouldn't the class be defined the first one? I can't check right now. Anyway, a test extending both, a class and an interface seems like a really good case to have a test. @guori-panda, can you add such test?

2022-07-05 13:23 UTC, amitdash291 commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClass.kt
> +            hasInheritedMember(true) -> return
@BraisGabin yes interestingly this is valid Kotlin code. A class can implement multiple interfaces and inherits from a class at the same time.

2022-07-06 20:11 UTC, gouri-panda commented
@BraisGabin @amitdash291 Sure :)

2022-07-07 14:13 UTC, BraisGabin reviewed
The PR still has conflicts.

2022-07-07 14:13 UTC, BraisGabin commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClassSpec.kt
> +                abstract class B: A(), I
```suggestion
                abstract class B: A(), I
                abstract class C: I, A()
```

We should check both cases.

2022-07-07 15:39 UTC, gouri-panda commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClassSpec.kt
> +                abstract class B: A(), I
Sure! Let me add another test case as well!

2022-07-09 07:35 UTC, amitdash291 commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClassSpec.kt
> +                abstract class B: A(), I
@gouri-panda I have an idea to solve this in a generic manner. If you're okay I can raise a PR on your fork branch `gouri-panda:fix-4753`?

2022-07-09 08:26 UTC, gouri-panda commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClassSpec.kt
> +                abstract class B: A(), I
I was thinking if we check one of the parent is abstract, then we can return. But go for it :)

2022-07-09 13:23 UTC, amitdash291 commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClassSpec.kt
> +                abstract class B: A(), I
@gouri-panda my idea was to check if all parents are interfaces, basically the complementary set of whether any parent is abstract. The reason being I'm unable to find any helper method indicating if the parent class is abstract.

2022-07-09 18:50 UTC, amitdash291 commented on detekt-rules-style/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryAbstractClassSpec.kt
> +                abstract class B: A(), I
@gouri-panda 
I have pushed my changes as a [PR to your fork's branch here](https://github.com/gouri-panda/detekt/pull/1).
In summary I have checked if not all the parents are interfaces, which is equivalent of the fact that at least one parent is abstract.
The [commit is here](https://github.com/gouri-panda/detekt/pull/1/commits/69b3fd32157890e824e84781471fc660a14a19fd) (there are a few other merge commits)

2022-07-10 10:06 UTC, BraisGabin approved these changes

2022-07-10 10:26 UTC, BraisGabin commented
Thanks for the fix @gouri-panda and @amitdash291

2022-07-10 10:26 UTC, merged