Avoid NPEs in Kotlin 1.7.20
detekt/detekt pull request #5163
Opened 2022-08-01 02:50 UTC by Goooler

Same fixes borrowed from https://github.com/square/wire/pull/2310.

2022-08-01 02:57 UTC, Goooler commented on detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/DetektJvm.kt
> +            ?: project.objects.sourceDirectorySet("empty", "Empty kotlin source set")
453338904bb67c57e54568fa3c4b051a5bf09543

2022-08-01 03:48 UTC, 3flex commented
This logic doesn't make sense to me - it seems that in the case of a null source set, a detekt task would still be created, but `source` would be set to an empty value - so we'd be left with a task that will be skipped with a `NO-SOURCE` status.

If we need to filter out null source sets (and it would be good to understand what change has been made in the Kotlin Gradle Plugin that led to the change in behaviour) that should be done in a way that skips registration of a task that won't execute. I'd suggest logging a warning would be a good idea in that case as well.

2022-08-01 03:49 UTC, 3flex requested changes
This logic doesn't make sense to me - it seems that in the case of a null source set, a detekt task would still be created, but `source` would be set to an empty value - so we'd be left with a task that will be skipped with a `NO-SOURCE` status.

If we need to filter out null source sets (and it would be good to understand what change has been made in the Kotlin Gradle Plugin that led to the change in behaviour) that should be done in a way that skips registration of a task that won't execute. I'd suggest logging a warning would be a good idea in that case as well.

2022-08-01 08:59 UTC, cortinico reviewed
Thanks for sending this over 🙏

2022-08-01 08:59 UTC, cortinico commented on detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/DetektJvm.kt
> +    private val SourceSet.kotlin: SourceDirectorySet
Is there a reason why this property is uppercase?

2022-08-01 09:02 UTC, Goooler commented on detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/DetektJvm.kt
> +    private val SourceSet.kotlin: SourceDirectorySet
It's lowercase.

2022-08-01 09:16 UTC, cortinico commented on detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/DetektJvm.kt
> +    private val SourceSet.kotlin: SourceDirectorySet
🤦 Yeah my bad, it's an extension property

2022-08-30 15:05 UTC, Goooler commented on detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/DetektJvm.kt
> +            classpath.setFrom(inputSource, compilation.compileDependencyFiles)
Seems we can merge `DetektJvm` into `DetektMultiplatform`, see https://github.com/Goooler/detekt/pull/3.

2022-09-07 22:51 UTC, cortinico commented
@3flex how do you feel about this change?

It looks promising on my end buy I'm lacking a bit of context. @Goooler could you expand on the PR description on why this is needed?

2022-09-11 22:52 UTC, 3flex commented
I support this change, using the new approach - I'd still like to know what's changing in Kotlin 1.7.20 that means we have to make this change now, but putting that aside, we should do this anyway because:

1. The concept of Conventions is deprecated in Gradle, and KGP will drop them soon enough, requiring changes like this
2. As Goooler pointed out, it should allow consolidation of logic between MPP and Java variants at some point
3. Something like this will be needed for #4465 

I just wish we had better test coverage!

2022-09-11 22:52 UTC, 3flex approved these changes

2022-09-11 23:14 UTC, cortinico commented
> The concept of Conventions is deprecated in Gradle, and KGP will drop them soon enough, requiring changes like this

TIL. Is this documented somehwere?

2022-09-11 23:42 UTC, 3flex commented
This is probably most relevant:

https://docs.gradle.org/current/userguide/upgrading_version_7.html#all_convention_deprecation

2022-10-05 08:34 UTC, BraisGabin commented
This is ready to merge, right? I would vote to merge it for 1.22.0-RC2.

2022-10-06 09:55 UTC, merged

2022-10-06 10:07 UTC, Goooler commented
https://github.com/detekt/detekt/actions/runs/3196227698/jobs/5217876383

Seems `org.jetbrains.kotlin.gradle.plugin.mpp.pm20.targets` was removed from Kotlin 1.7.20, I'll fix it later.