Remove rule from NamingRules multi rule
detekt/detekt pull request #5212
Opened 2022-08-10 08:55 UTC by VovaStelmashchuk

This is part of #5192

2022-08-16 20:16 UTC, VovaStelmashchuk commented
@marschwar The merge request ready for review.

2022-08-17 10:39 UTC, cortinico requested changes

2022-08-17 10:39 UTC, cortinico commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/NamingProvider.kt
> +            VariableMaxLength(config),
That's a duplicate

2022-08-17 10:40 UTC, cortinico commented on detekt-rules-naming/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/NamingProvider.kt
> +            VariableMaxLength(config),
My bad that's on a old commit

2022-08-21 14:50 UTC, BraisGabin approved these changes

2022-08-21 14:50 UTC, BraisGabin commented on detekt-rules-coroutines/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/coroutines/SuspendFunWithCoroutineScopeReceiverSpec.kt
> +                import kotlinx.coroutines.CoroutineScope
It this change related with this PR?

2022-08-21 14:53 UTC, VovaStelmashchuk commented on detekt-rules-coroutines/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/coroutines/SuspendFunWithCoroutineScopeReceiverSpec.kt
> +                import kotlinx.coroutines.CoroutineScope
No, I bad, it is just a fix, because the test was red. The branch `main` has the same changes

2022-09-10 09:39 UTC, BraisGabin commented
@cortinico is there anything else that should be changed here?

2022-09-10 09:41 UTC, cortinico approved these changes

2022-09-10 09:41 UTC, cortinico commented
> @cortinico is there anything else that should be changed here?

Nope we can merge it 👍

2022-09-10 09:41 UTC, merged

2022-09-10 09:52 UTC, BraisGabin commented
@VovaStelmashchuk Thanks for this PR :)