Configure languageVersion via toolchain
detekt/detekt pull request #5735
Opened 2023-01-27 18:23 UTC by Goooler

Follow up #5614.

https://kotlinlang.org/docs/gradle-configure-project.html#gradle-java-toolchains-support

2023-01-27 20:15 UTC, schalkms approved these changes

2023-01-27 22:23 UTC, 3flex requested changes
I did something very similar in https://github.com/detekt/detekt/pull/5676 and reverted in https://github.com/detekt/detekt/pull/5685 because:

> The original PR only was only half a solution - it meant that all builds effectively ran on Java 1.8 regardless of which Java version the Gradle build was running. This is fine for the main source build but not for tests, which we want to run on multiple Java versions.

If you can make updates to allow for that then I'd be happy to approve but there'll likely be config changes to a few places in the build and potentially the GitHub workflows as well.

2023-01-28 03:12 UTC, Goooler commented
The solution might be [Build on latest Java, test through lowest Java](https://jakewharton.com/build-on-latest-java-test-through-lowest-java), but there is a `NoSuchMethodError` in `detekt-compiler-plugin` test

```sh
CompilerTest > with a source file that contains violations() FAILED
    java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.cli.common.arguments.K2JVMCompilerArguments.setSingleModule(boolean)'
        at app//com.tschuchort.compiletesting.KotlinCompilation$commonK2JVMArgs$1.invoke(KotlinCompilation.kt:359)
        at app//com.tschuchort.compiletesting.KotlinCompilation$commonK2JVMArgs$1.invoke(KotlinCompilation.kt:300)
        at app//com.tschuchort.compiletesting.AbstractKotlinCompilation.commonArguments(AbstractKotlinCompilation.kt:133)
        at app//com.tschuchort.compiletesting.KotlinCompilation.commonK2JVMArgs(KotlinCompilation.kt:300)
        at app//com.tschuchort.compiletesting.KotlinCompilation.compileJvmKotlin(KotlinCompilation.kt:488)
        at app//com.tschuchort.compiletesting.KotlinCompilation.compile(KotlinCompilation.kt:664)
        at app//io.github.detekt.compiler.plugin.util.CompilerTestUtils.compile(CompilerTestUtils.kt:21)
        at app//io.github.detekt.compiler.plugin.CompilerTest.with a source file that contains violations(CompilerTest.kt:11)
```

2023-01-28 09:29 UTC, 3flex commented
The `test` task is currently disabled on `detekt-compiler-plugin`, so these auto generated tasks should be disabled on that project too.

2023-01-28 10:04 UTC, Goooler commented
Disabled. Let's see the impacts on build time.

2023-01-28 21:49 UTC, 3flex commented
Yeah that was going to be my next point, but I wanted to see the actual CI runtimes first.

They're not good (which is expected). The loss of parallelism for test execution on the different JVM versions really hurts. This tradeoff isn't worth it just to use toolchains.

2023-01-29 19:45 UTC, cortinico commented
> The loss of parallelism for test execution on the different JVM versions really hurts.

+1 for this. I'd rather keep explicit Java versions in the CI matrix as it's also easier for users to understand which version of Java broke

2023-01-30 01:54 UTC, Goooler commented
Agreed, I'll leave this PR open until we find new way to optimize.

2023-03-20 03:39 UTC, Goooler commented
I'm not sure why builds on Windows are still failing after applying `foojay-resolver-convention`, but the build time on Ubuntu looks resonable.

2023-03-20 04:12 UTC, Goooler commented
It looks fine for now.

2023-03-20 14:10 UTC, cortinico commented on detekt-gradle-plugin/settings.gradle.kts
> +    id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"
Why is this needed?

2023-03-20 14:30 UTC, Goooler commented on detekt-gradle-plugin/settings.gradle.kts
> +    id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"
For Windows, check https://github.com/detekt/detekt/actions/runs/4464478367/jobs/7840655669

2023-05-29 16:50 UTC, chao2zhang commented
Is this PR still blocked? Could we make a call on whether to move forward or to close this?

2023-06-02 17:35 UTC, cortinico commented
My 2 c here: I'd love us to use `jvmToolchain` here but I'm not a big fan on adding yet another Gralde plugin to handle the Win case. So I'd rather close this for now and get back to it?

2023-06-04 22:58 UTC, 3flex commented on detekt-gradle-plugin/settings.gradle.kts
> +    id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"
It's not needed for Windows specifically, it's required any time a requested JDK is not found locally. It's a requirement in most cases if using toolchains.

More here: https://docs.gradle.org/current/userguide/toolchains.html#sub:download_repositories

2023-06-05 01:46 UTC, Goooler commented on detekt-gradle-plugin/settings.gradle.kts
> +    id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"
Yep.

2023-09-08 07:42 UTC, 3flex commented
I'm going to close this, though not because of the foojay plugin (that's essentially a requirement to use toolchains outside of controlled environments where JDKs are all pre installed).

Instead I'd like to wait until this is ready later this year: https://github.com/gradle/build-tool-roadmap/issues/61

We can then just use a standard config to set up the test suites instead of developing a custom one. Things are working ok as they are so there's no real reason to switch yet.

2023-09-08 07:42 UTC, closed without merging