Fix generateDocumentation implicit dependencies
detekt/detekt pull request #5773
Opened 2023-02-09 09:39 UTC by jprinet

The `:detekt-rules-libraries:processResources` and `:detekt-rules-authors:processResources` tasks have an implicit dependency on `:detekt-generator:generateDocumentation` task, the files `detekt-rules-libraries/src/main/resources/config/config.yml` and `detekt-rules-ruleauthors/src/main/resources/config/config.yml` being outputs of `:detekt-generator:generateDocumentation`.

This has a small impact on performances (see [here](https://ge.detekt.dev/s/ltywkmui6n6ka/timeline?cacheability=validation-failure#6q6tf2ndv5xfi) an example on `detekt-rules-authors:processResources`)

This PR fixes this by [sharing the artifacts through a Gradle configuration](https://docs.gradle.org/current/userguide/cross_project_publications.html#sec:simple-sharing-artifacts-between-projects).

Please note that I had to cut some task dependencies in `detekt-generator` build script to avoid a cycle in the task graph (`assemble` => `build` => `shadowJar` => `generateDocumentation` => `assemble`). Please review those carefully as I am not familiar enough with the codebase to measure the impacts.

2023-02-09 09:52 UTC, 3flex commented
Thanks! This should fix https://github.com/detekt/detekt/issues/5768. I (or someone) will review when I get some time.

2023-02-09 12:36 UTC, TWiStErRob requested changes
Really nice fix, thank you for noticing and implementing a change!

I left a few comments which are mostly thoughts that came to my head during review. Feel free to discuss if it doesn't improve the code or not clear.

Note: I'm new to Detekt, that's why I tagged @3flex on a few things.

2023-02-09 12:36 UTC, TWiStErRob commented on detekt-generator/build.gradle.kts
> +        builtBy(generateDocumentation)
@3flex Probably out of the scope of this PR, but realistically maybe these files should be generated by separate tasks? Because they're not documentation.

2023-02-09 12:36 UTC, TWiStErRob commented on detekt-generator/build.gradle.kts
> +}
The path of these files are outside this module, so by default `src/main/resources` input of `processResources` of those modules will pick it up. Which means exposing and adding the configuration dependency only exists to make the tasks work. But I guess this is the original problem.

I wonder if it would make sense to relocate those files into the generator module, and pull the artifacts via configuration from the others. In this case the explicit dependency would make more sense (be more clear) and also there wouldn't be overlap between an input folder (src) and an output file (that should be under `build`, really). Although they're version controlled, and in that case their location that makes sense.

I noticed that `gradlew :detekt-generator:clean` doesn't actually delete these files, while `gradlew :detekt-generator:cleanGenerateDocumentation` does, and also breaks the next build. Anyway, I'm digressing a bit too much.

I think because of the source-controlled files, it makes sense to leave it this way. I would like @3flex to read this and ack it, and then I think this conversation can be resolved, because I convinced myself it's good as it is :)

2023-02-09 12:36 UTC, TWiStErRob commented on detekt-generator/build.gradle.kts
> +val generateDocumentationConfigurationLibraries: Configuration by configurations.creating {
I see why you used `generateDocumentation` as a prefix (task name), but it's a bit hard to grasp at glance what this actually is, because it's actually the generated configuration file for a specific published maven artifact (detekt ruleset jar), not doc.

Here are two proposals, I would pick the first, because it's a bit more consistent naming with only a prefix, and a varying suffix, while in the second the changing part is in the middle.
```suggestion
val generatedConfigForLibraries: Configuration by configurations.creating {
```
```suggestion
val generatedLibrariesConfig: Configuration by configurations.creating {
```

Also note that the fact that this is builtBy `generateDocumentation` is an implementation detail that shouldn't leak to other modules.

2023-02-09 12:36 UTC, TWiStErRob commented on detekt-rules-ruleauthors/build.gradle.kts
> +val generateDocumentationConfiguration: Configuration by configurations.creating {
Would there be a way to share this logic between the two modules?

For example: `fun Project.consumeGeneratedConfig(configurationName: String)` which does these 3 things (create config, add dep, configure resources task). This can be created in as `build-logic/src/main/kotlin/consumeGeneratedConfig.kt` (no package directive)

Then all the changes in this file can be replaced with
```gradle
consumeGeneratedConfig("generatedConfigForRuleauthors")
```

Before you make this change, let's see if @3flex gives a thumbs up.

2023-02-09 12:36 UTC, TWiStErRob commented on detekt-generator/build.gradle.kts
> +val generateDocumentationConfigurationLibraries: Configuration by configurations.creating {
Should this be lazy?
```suggestion
val generateDocumentationConfigurationLibraries by configurations.registering {
```

2023-02-09 12:44 UTC, TWiStErRob commented on detekt-rules-libraries/build.gradle.kts
> +        .withPathSensitivity(PathSensitivity.RELATIVE)
seems to be safely hardcoded:
https://github.com/detekt/detekt/blob/36fa0a68ea035d1554f42f14586698e2d36c5013/detekt-utils/src/main/kotlin/io/github/detekt/utils/Yaml.kt#L3-L14

2023-02-09 13:16 UTC, TWiStErRob commented on detekt-rules-ruleauthors/build.gradle.kts
> +    )
Probably better on single-line as other dependencies?

Also I saw you were trying to use the DSL... `projects.detektGenerator.dependencyProject.path` works, but a bit wordy.

2023-02-09 13:16 UTC, jprinet commented on detekt-rules-libraries/build.gradle.kts
> +    )
Thanks for the hint, let's go with your first proposal 👍

2023-02-09 13:20 UTC, jprinet commented on detekt-rules-libraries/build.gradle.kts
> +        .withPathSensitivity(PathSensitivity.RELATIVE)
This is required for cache relocatability, the idea is to only rely on the [relative](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/PathSensitivity.html#RELATIVE) part of the file path when computing the cache key. This allow to have cache hits when the project has a different clone location, which is usually the case.

2023-02-09 13:29 UTC, jprinet commented on detekt-generator/build.gradle.kts
>  val generateDocumentation by tasks.registering(JavaExec::class) {
This one didn't pop in the list of tasks for which optimizations were disabled, not sure why. 
I would only pass artifacts through configuration if required.

2023-02-09 13:35 UTC, jprinet commented on detekt-generator/build.gradle.kts
> +}
Having task outputs in the regular `build` directory is our recommendation.
I think that having them transferred from there to the consumer module (int its `build` directory) would be cleaner.

2023-02-09 13:37 UTC, jprinet commented on detekt-rules-ruleauthors/build.gradle.kts
> +    )
Yep, I would have preferred the `path` at the upper level, I reverted to string thus. No strong opinion though.

2023-02-09 16:16 UTC, TWiStErRob commented on detekt-rules-libraries/build.gradle.kts
> +        .withPathSensitivity(PathSensitivity.RELATIVE)
Yeah, I understand that, I'm proposing to make `\r\n` relocatable (this = `normalizeLineEndings`, sorry that wasn't clear), but it's not necessary with these files.

2023-02-09 16:24 UTC, TWiStErRob commented on detekt-generator/build.gradle.kts
> +}
In my understanding that would need [a separate task](https://github.com/detekt/detekt/pull/5773#discussion_r1101364917), right? So it's easy to move around.

2023-02-09 16:26 UTC, TWiStErRob commented on detekt-rules-ruleauthors/build.gradle.kts
> +    )
Is it worth opening a Gradle issue for `.path` on accessor level?
Also it should be quite easy to just write an extension function in default package in `build-logic`: `val ProjectDependency.path: String = dependencyProject.path`, which means it would be trivially visible immediately to all build files.

2023-02-09 16:44 UTC, TWiStErRob commented on detekt-generator/build.gradle.kts
> +val generateDocumentationConfigurationLibraries: Configuration by configurations.creating {
~I think that's acceptable, any laziness win counts, as they add up.~ That said, I couldn't prove that its creation is actually delayed. This is because when an item is registered in `DefaultDomainObjectCollection`, it might actually realize the item, if there are "listeners" registered in `eventRegister`. This shows that there are 3 listeners in `project.configurations`:
so all the configurations will be always immediately realized (in Kotlin modules or even where the `base` plugin is applied).

![image](https://user-images.githubusercontent.com/2906988/217879756-d137951e-5da1-4c54-85db-62ef1b57454f.png)

This means that `.creating` will be just as good, and we can use the `"`.

---

Note: Gradle base plugin is eagerly creating all configurations here:
`org.gradle.api.plugins.BasePlugin#configureConfigurations`: `configurations.all { }`

2023-02-09 17:18 UTC, TWiStErRob commented
Note: there might've been some hidden conversations:
![image](https://user-images.githubusercontent.com/2906988/217889104-52292fae-b58f-4fef-b787-64094818471f.png)

2023-02-09 18:32 UTC, TWiStErRob commented on detekt-generator/build.gradle.kts
>  val generateDocumentation by tasks.registering(JavaExec::class) {
Here's a consistent repro for the libraries module (shows warning on main, works on PR):
```
gradlew :detekt-generator:cleanGenerateDocumentation :detekt-generator:generateDocumentation :detekt-rules-libraries:cleanProcessResources :detekt-rules-libraries:processResources --no-build-cache
```
I've tried to reproduce the `formatting` one too, but it's very elusive. `formatting:processResources` executes way before `genereateDoc` so it doesn't trigger the warning. even with explicit ordering this is the case:
```
gradlew :detekt-generator:cleanGenerateDocumentation :detekt-generator:generateDocumentation :detekt-formatting:cleanProcessResources :detekt-formatting:processResources --no-build-cache --no-parallel
```
with a build scan (click images below for build scan link) I was able to see the dependency chain:
[![image](https://user-images.githubusercontent.com/2906988/217904393-949e6744-a796-4c2f-86b2-6d7db30e3839.png)](https://scans.gradle.com/s/ptk3dssf5ve74/timeline?details=obip45c7m6nay&expanded=WyIwLjYwIiwiMC42MC0xLjYxIiwiMC42MC0xLjYxLTIuMTUxIl0&show=successors)
while for libraries there's no such chain:
[![image](https://user-images.githubusercontent.com/2906988/217905363-5c302a08-2fde-4157-ae9c-85af1c64ff55.png)](https://scans.gradle.com/s/fxgtfhzfeau2i/timeline?details=kk3t5ppvxtweg&show=successors)

2023-02-09 18:50 UTC, TWiStErRob commented on detekt-generator/build.gradle.kts
>  val generateDocumentation by tasks.registering(JavaExec::class) {
See https://github.com/detekt/detekt/pull/5777/files#diff-ea59b2a3d3e92b5338889a89da73aa371f1e84fb6117576240f0f3cc5d1b5c4fR169-R173

@3flex what can we do here? I think breaking the dependency will allow for this PR to apply to the formatting module too, but the root cause is that the config file generation and the documentation generation are bundled together into one module/class.

2023-02-10 08:56 UTC, jprinet commented on detekt-rules-libraries/build.gradle.kts
> +        .withPathSensitivity(PathSensitivity.RELATIVE)
oh sorry I just missed the extra line in the suggestion. As you said, nothing to add given the implementation 👍
Another way to handle that is to configure it in `Git`.

2023-02-10 09:02 UTC, jprinet commented on detekt-generator/build.gradle.kts
> +val generateDocumentationConfigurationLibraries: Configuration by configurations.creating {
Thanks for the detailed explanation, that's definitely helpful. I'll revert to the `.creating` approach

2023-02-10 11:46 UTC, TWiStErRob commented on detekt-generator/build.gradle.kts
> +    add(generatedRulesConfig.name, file(ruleauthorsConfigFile)) {
would you mind renaming this to
```suggestion
    add(generatedRuleauthorsConfig.name, file(ruleauthorsConfigFile)) {
```
"rulesconfig" sounds like it's all the rules.

2023-02-10 12:47 UTC, jprinet commented on detekt-rules-libraries/build.gradle.kts
> +tasks.withType<ProcessResources>().configureEach {
done 👍

2023-02-10 12:52 UTC, jprinet commented on detekt-rules-ruleauthors/build.gradle.kts
> +    )
Added an E`xtensions.kt` in the `build-logic` to support this

2023-02-10 12:52 UTC, jprinet commented on detekt-generator/build.gradle.kts
> +    add(generatedRulesConfig.name, file(ruleauthorsConfigFile)) {
done 👍

2023-02-10 14:39 UTC, TWiStErRob commented on detekt-rules-libraries/build.gradle.kts
> +    )
I think it would be better to keep them similar to other dependencies (it probably fits easily):
```suggestion
    generatedLibrariesConfig(project(projects.detektGenerator.path, "generatedLibrariesConfig"))
```

2023-02-10 14:44 UTC, TWiStErRob commented on detekt-rules-libraries/build.gradle.kts
> +tasks.named<ProcessResources>("processResources").configure {
oh, it seems we don't need this, Task.inputs is visible anyway.
```suggestion
tasks.named("processResources").configure {
```

2023-02-10 14:45 UTC, TWiStErRob approved these changes
Only 3 tiny nits, waiting for @3flex now.

2023-02-10 14:49 UTC, TWiStErRob commented on detekt-rules-ruleauthors/build.gradle.kts
> +val generatedRuleauthorsConfig: Configuration by configurations.creating {
What do you think about naming these consuming configs the same in every module?
```suggestion
val generatedConfig: Configuration by configurations.creating {
```

Having the same name kind-of suggests that their names have to match, which isn't true. Having the same name also looks confusing at usage, compare:
`generatedRuleauthorsConfig(project(detektGenerator, "generatedRuleauthorsConfig"))`
vs
`generatedConfig(project(detektGenerator, "generatedRuleauthorsConfig"))`

2023-02-10 14:56 UTC, jprinet commented on detekt-rules-libraries/build.gradle.kts
> +    )
👍

2023-02-10 14:57 UTC, jprinet commented on detekt-rules-libraries/build.gradle.kts
> +tasks.named<ProcessResources>("processResources").configure {
indeed 👍

2023-02-10 14:58 UTC, jprinet commented on detekt-rules-ruleauthors/build.gradle.kts
> +val generatedRuleauthorsConfig: Configuration by configurations.creating {
Yes, I agree about the confusion and it was tempting to convert the string to the variable name although representing different things.
Let's name the consumer configuration as per your suggestion 👍

2023-02-11 00:15 UTC, big-guy commented on detekt-rules-ruleauthors/build.gradle.kts
> +    )
I wouldn't add extensions to do this.  If anything, we should remove `dependencyProject` from `ProjectDependency`. 

I would do this:
```
generatedRulesConfig(projects.detektGenerator) {
        targetConfiguration = "generatedRulesConfig"
}
```

This uses the accessor as it was intended and avoids the Kotlin DSL specific `project(String, String)` method.

2023-02-11 08:53 UTC, TWiStErRob commented on detekt-rules-ruleauthors/build.gradle.kts
> +    )
Nice! Thank you! I agree.

2023-02-11 09:02 UTC, TWiStErRob commented on detekt-rules-ruleauthors/build.gradle.kts
> +val generateDocumentationConfiguration: Configuration by configurations.creating {
I think now that there are 3 instances and a 4th one looming (formatter), I would go ahead with this. Considering we need to parameterize on task as well:

```
consumeGeneratedConfig(for = "processResources", from = "generatedRuleauthorsConfig")
```
?

2023-02-14 09:43 UTC, jprinet commented on detekt-rules-ruleauthors/build.gradle.kts
> +val generateDocumentationConfiguration: Configuration by configurations.creating {
This is way cleaner with your suggestion 👍

2023-02-15 11:42 UTC, 3flex approved these changes

2023-02-15 11:43 UTC, 3flex commented
Nice work! Thanks for taking the time to do this, and thanks to TWiStErRob and big-guy for reviewing.

2023-02-15 11:43 UTC, merged

2023-02-15 12:05 UTC, 3flex commented
Unfortunately there's an error that only came up after merging, as none of the PR CI jobs just run a plain `./gradlew build`.

But that's run before deploying a snapshot and it failed with:
```
Circular dependency between the following tasks:
:detekt-formatting:build
\--- :detekt-formatting:check
     \--- :detekt-formatting:detekt
          +--- :detekt-rules-libraries:jar
          |    \--- :detekt-rules-libraries:classes
          |         \--- :detekt-rules-libraries:processResources
          |              \--- :detekt-generator:generateDocumentation
          |                   +--- :detekt-formatting:build (*)
          |                   \--- :detekt-rules:build
          |                        \--- :detekt-rules:check
          |                             \--- :detekt-rules:detekt
          |                                  +--- :detekt-rules-libraries:jar (*)
          |                                  \--- :detekt-rules-ruleauthors:jar
          |                                       \--- :detekt-rules-ruleauthors:classes
          |                                            \--- :detekt-rules-ruleauthors:processResources
          |                                                 \--- :detekt-generator:generateDocumentation (*)
          \--- :detekt-rules-ruleauthors:jar (*)

(*) - details omitted (listed previously)
```
https://ge.detekt.dev/s/2xn35555wzg4q/failure#1
https://github.com/detekt/detekt/actions/runs/4183501703/jobs/7247933889

2023-02-15 12:38 UTC, jprinet commented
Commenting those 2 `finalizedBy` instructions helps to get rid of the circular dependency
https://github.com/detekt/detekt/blob/a6d81feef18c4719e810b63e2acbd2810870bf62/detekt-rules/build.gradle.kts#L31
https://github.com/detekt/detekt/blob/a6d81feef18c4719e810b63e2acbd2810870bf62/detekt-formatting/build.gradle.kts#L26

2023-02-15 15:51 UTC, jprinet commented
> Unfortunately there's an error that only came up after merging, as none of the PR CI jobs just run a plain `./gradlew build`.

See https://github.com/detekt/detekt/pull/5792 for resolution