Add TodoWithoutLink rule
detekt/detekt pull request #5926
Opened 2023-03-22 14:23 UTC by AndreuZaitsev

Checks whether comment or documentation has TODO without a web-link.

2023-03-23 09:00 UTC, cortinico commented
Forcing TODOs to have a specific link seems like maybe too specific. I think we should make the Regex `DEFAULT_LINK_PATTERN = """\bhttps?://(?:www\d?)?[\w/#&?=\-.]+\b"""` configurable so that users can specify how their TODO should look like.

For example people might want to enforce a `TODO (username): text` or a `TODO #githubissuenumber`. If so, the rule should also be renamed

2023-03-23 09:31 UTC, AndreuZaitsev commented
> Forcing TODOs to have a specific link seems like maybe too specific. I think we should make the Regex `DEFAULT_LINK_PATTERN = """\bhttps?://(?:www\d?)?[\w/#&?=\-.]+\b"""` configurable so that users can specify how their TODO should look like.
> 
> For example, people might want to enforce a `TODO (username): text` or a `TODO #githubissuenumber`. If so, the rule should also be renamed

Yup, could not agree more on that. 
So, custom pattern can be provided using config, right? 
```Kotlin
@Configuration("custom link regex pattern")
private val linkRegexPattern: String by config(DEFAULT_LINK_PATTERN)
```

As for having username or something else, it also can be configured using more complex regex pattern.

So, yes, since regex can be whatever user wants it to be, this can be renamed a bit no to be specific on web links.

2023-03-24 21:43 UTC, schalkms requested changes
Did you check the `ForbiddenImport` rule whether this is already covered by rule configs?
https://detekt.dev/docs/rules/style/#forbiddencomment

2023-03-26 11:31 UTC, BraisGabin commented
I feel this rule is far too specific to fit inside the default rule set.

But it would be a great addition for a third party rule set. We could have it listed on our market place.

2023-04-02 18:39 UTC, schalkms commented
@AndreuZaitsev may I ask you to publish this rule somewhere? Then submit a new PR, which adds a link to the detekt marketplace. It would be great to have this rule added to the marketplace.

2023-04-02 18:39 UTC, closed without merging