Report the usage unnecessary function to invoke a lambda argument
detekt/detekt pull request #6005
Opened 2023-04-15 23:21 UTC by atulgpt

Implements https://github.com/detekt/detekt/issues/5836

2023-04-16 10:28 UTC, cortinico requested changes
The rule logic is quite intricated. Can we vendor the `ConvertLambdaToReferenceIntention.kt` file and keep the rule logic smaller?

2023-04-16 10:28 UTC, cortinico commented on detekt-rules-performance/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/performance/UnnecessaryLambda.kt
> + * inline fun test1(lambda: () -> Unit) {
```suggestion
 * inline fun test(lambda: () -> Unit) {
```

2023-04-16 10:28 UTC, cortinico commented on detekt-rules-performance/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/performance/UnnecessaryLambda.kt
> + *         // no compliant
This comment can be removed

2023-04-16 10:28 UTC, cortinico commented on detekt-rules-performance/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/performance/UnnecessaryLambda.kt
> + * // compliant
Similarly I will remove all the `//compliant` comment here

2023-04-16 10:28 UTC, cortinico commented on detekt-rules-performance/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/performance/UnnecessaryLambda.kt
> +                    "Xc"
This is missing

2023-04-16 18:25 UTC, atulgpt commented
> Can we vendor the `ConvertLambdaToReferenceIntention.kt` file and keep the rule logic smaller?

Currently, I have exactly the same code as `ConvertLambdaToReferenceIntention.kt` same is being followed in other rules as well. What benefits will it serve to keep the code to `ConvertLambdaToReferenceIntention.kt` as it doesn't follow the existing convention and later if we want to add configs, or modify the behaviour of the rule it will be difficult to add those in separate `ConvertLambdaToReferenceIntention.kt`

But if you still feel that it should in separate file then I will change this

2023-04-16 18:40 UTC, atulgpt commented on detekt-rules-performance/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/performance/UnnecessaryLambda.kt
> + *         // no compliant
Done

2023-04-16 18:40 UTC, atulgpt commented on detekt-rules-performance/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/performance/UnnecessaryLambda.kt
> +                    "Xc"
Added

2023-04-16 18:41 UTC, atulgpt commented
Hi @cortinico / @BraisGabin any idea how to run tests against different Kotlin version?

2023-04-16 19:19 UTC, marschwar commented on detekt-rules-performance/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/performance/UnnecessaryLambda.kt
> + * listOf(1).map { toDomain(it) }
Why is this code compliant? When I put this snippet into a kotlin file it does not compile.

2023-04-16 19:29 UTC, atulgpt commented on detekt-rules-performance/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/performance/UnnecessaryLambda.kt
> + * listOf(1).map { toDomain(it) }
Did you put
```
fun toDomain(i: Int) = i.toString()
listOf(1).map { toDomain(it) }
```

both the lines?

2023-04-16 19:36 UTC, marschwar commented on detekt-rules-performance/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/performance/UnnecessaryLambda.kt
> + * penalty when compared to directly passing lambda variable.
Do we have documentation, benchmarks that we could link to further explain the issue? I do not like that we state this as a fact and do not show proof. People might blindly follow the advice without second guessing it. I know I would.

I came across [this post](https://dev.to/vtsen/prefer-function-reference-over-lambda-in-kotlin-wrong-1f8k). I have no idea how credible it is. Does the performance penalty depend on the kotlin compiler version?

2023-04-16 19:51 UTC, marschwar commented on detekt-rules-performance/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/performance/UnnecessaryLambda.kt
> + * penalty when compared to directly passing lambda variable.
And applies the performance penalty to all output targets?

2023-04-16 19:53 UTC, atulgpt commented on detekt-rules-performance/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/performance/UnnecessaryLambda.kt
> + * penalty when compared to directly passing lambda variable.
Hi, @marschwar, I did not run any benchmark on it. My initial motivation was to prohibit below type of use-case
```
fun test(lambda: () -> Unit) {
    thread {
        lambda()
    }.start()
}
```
and prompt below alternate code
```
fun test(lambda: () -> Unit) {
    thread(block = lambda).start()
}
```

But yes I agree that it will not be beneficial for all the use cases. I have also added `This **may** have` implying that it will not be the case always.

Finally, this rule promotes function ref for all the cases for consistency. But I am also open to suggestions

2023-04-16 20:39 UTC, marschwar commented on detekt-rules-performance/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/performance/UnnecessaryLambda.kt
> + * penalty when compared to directly passing lambda variable.
I think your original use case is quite different to what this ended up being. I am sorry, I should have made those points before you put in all the work. 

I do not think that we should promote function references as there are many cases where it is not possible to use a function reference and therefor you might end up with a mix of function refs and lambdas in the same map chain.

Just out of curiosity I decompiled the generated kotlin byte code for the compliant and non-compliant version with IntelliJ and ended up with exactly the same java code. I do not have any experience with this feature but at first sight I do not think detekt should claim that this is or may be a performance issue unless we know for a fact in which circumstances that is the case. 

BTW: Your original use case actually does generate an extra anonymous function in the non-compliant version making it a good candidate for a rule.

2023-04-16 20:48 UTC, marschwar commented on detekt-rules-performance/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/performance/UnnecessaryLambda.kt
> + * penalty when compared to directly passing lambda variable.
Interestingly the kotlin compiler seems to do some optimizations as both functions below are decompiled into nearly the same java code.

```kotlin
fun compliant(lambda: (Int) -> Unit) {
    repeat(3, lambda)
}
// and
fun nonCompliant(lambda: (Int) -> Unit) {
    repeat(3) { n -> lambda(n) }
}
```

In this case it may just be a matter of style.

2023-04-16 20:58 UTC, atulgpt commented on detekt-rules-performance/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/performance/UnnecessaryLambda.kt
> + * penalty when compared to directly passing lambda variable.
It is because `repeat` is `inline fun`

2023-04-17 14:12 UTC, cortinico commented
> But if you still feel that it should in a separate file then I will change this

I think that this case might be worth to have the copied logic in a separate file. The reason is that it's quite extensive and hard to isolate. So if we need to update the vendored logic, it should be easier

2023-04-19 15:25 UTC, BraisGabin commented
To me this is not a performance rule. It is a style rule. Probably a controversial style rule. But I think like the idea of this rule.

2023-04-19 16:29 UTC, marschwar commented
I think it should be moved to the style rule set. But before you put in more work we should decide on the rule focus. should we do that on the original issue?
I do not like us recommending function references for no apparent reason. To me this feels like is own rule.

2023-04-20 13:27 UTC, BraisGabin commented
Moving the conversation back to the issue: https://github.com/detekt/detekt/issues/5836#issuecomment-1516328660 so we can talk more about it there.

2023-05-07 08:41 UTC, marschwar commented
I believe this PR is obsolete now since we decided to go back to the drawing board. Can we close it @atulgpt ?

2023-05-07 09:23 UTC, closed without merging