Add wrapper for KtLint rules
detekt/detekt pull request #6037
Opened 2023-04-24 14:12 UTC by atulgpt

Fixes https://github.com/detekt/detekt/issues/5627

2023-04-24 14:31 UTC, cortinico requested changes

2023-04-24 14:31 UTC, cortinico commented on detekt-core/src/main/resources/default-detekt-config.yml
> +    active: false
Why this changed?

2023-04-24 14:31 UTC, cortinico commented on detekt-formatting/src/main/resources/config/config.yml
> +  ClassNaming:
I would call this differently like `ClassNamingKtlint` or `ClassNamingFormatting` or `ClassNamingWrapper`

2023-04-24 15:52 UTC, atulgpt commented on detekt-core/src/main/resources/default-detekt-config.yml
> +    active: false
Yes, that was my [question](https://github.com/detekt/detekt/issues/5627#issuecomment-1519057082). Ideally it should not be changed but automatically changed. This could be a bug as I have also added the `ClassNaming` rule from KtLint and there was one preexisting `ClassNaming` rule as well

2023-04-24 15:53 UTC, atulgpt commented on detekt-formatting/src/main/resources/config/config.yml
> +  ClassNaming:
But do we want `ClassNaming` rule from `Ktlint`? Shouldn't the detekt one be preferred over `KtLint` one? Or do we want to deprecate ours in favour of `KtLint`?

2023-04-25 00:38 UTC, 3flex commented on detekt-formatting/src/main/resources/config/config.yml
> +  ClassNaming:
Yeah I don't know about that naming either, it breaks with convention (it would be the only ktlint rule that has a suffix like that).

Could just call it `ClassName`?

It's true we have duplication between rules but this isn't something we need to solve here.

2023-04-25 00:46 UTC, 3flex commented
I believe these rules are all enabled by default in ktlint so to keep with convention we would enable them by default here too?

Or do we make an exception and keep them disabled when detekt has an equivalent rule

2023-04-25 07:53 UTC, atulgpt commented
> Or do we make an exception and keep them disabled when detekt has an equivalent rule

We should not make two different rules enabled. That can potentially cause problems due to conflicting analysis

2023-04-25 07:58 UTC, atulgpt commented on detekt-core/src/main/resources/default-detekt-config.yml
> +    active: false
In other words, in `detekt` what is a unique identifier for a rule? Is this just rule name or combination of rule provider id and name?

2023-04-25 10:53 UTC, cortinico commented on detekt-core/src/main/resources/default-detekt-config.yml
> +    active: false
> how we handle the same name rules, should generateDocumentation fail in cases like that?

I think that's a bug and we should investigate here. Rules with same ID coudl occur, especially if coming from external packages.

2023-04-25 10:53 UTC, cortinico commented on detekt-formatting/src/main/resources/config/config.yml
> +  ClassNaming:
Yup I'm fine with any name, as long as it doens't clash with one of our rule we already have

2023-04-25 14:37 UTC, atulgpt commented on detekt-formatting/src/main/resources/config/config.yml
> +  ClassNaming:
I have changed the name to `ClassName`

2023-04-30 02:43 UTC, 3flex approved these changes

2023-04-30 13:57 UTC, cortinico approved these changes

2023-04-30 13:57 UTC, merged