Dynamically set the ktlint version in rule docs
detekt/detekt pull request #6103
Opened 2023-05-15 22:35 UTC by marschwar

This fixes #6099 

As my gradle skills are still quite limited, this is an uninformed attempt to dynamically set the ktlint rule links to the currently used version. Please let me know if there are better ways to accomplish this.

2023-05-16 07:56 UTC, TWiStErRob reviewed
I was about to report the same issue, nice fix with the rewiring!

2023-05-16 07:56 UTC, TWiStErRob commented on build-logic/src/main/kotlin/CopyDirTask.kt
> +    abstract val source: DirectoryProperty
Hmm, feels like this should fail or at least warn about PathSensitivity.

2023-05-16 07:56 UTC, TWiStErRob commented on detekt-generator/build.gradle.kts
> +    outputs.files(fileTree(documentationDir))
No need for explicit listing, the annotations on the task properties are here exactly to do this.

2023-05-16 07:56 UTC, TWiStErRob commented on build-logic/src/main/kotlin/CopyDirTask.kt
> +        fs.copy {
I learned recently that you never want to use `copy` in Gradle, but `sync`. The difference is that `copy` doesn't clean the output, so if there's a file removed in input, it'll still exists after the operation.

2023-05-16 07:56 UTC, TWiStErRob commented on detekt-generator/build.gradle.kts
> +val copyRuleDocsToWebsite by tasks.registering(CopyDirTask::class) {
I think the custom task might not be necessary:
```kotlin
val copyRuleDocsToWebsite by tasks.registering(Sync::class) {
	from(tempDocDir)
	into(documentationDir)
	val replacements = mapOf(
		"KTLINT_VERSION" to libs.versions.ktlint.get(),
                // Added benefit: future replacement can be just added here without any other changes.
	)
	// For up to date checks, see https://github.com/gradle/gradle/issues/861.
	replacements.forEach { (name, value) -> inputs.property(name, value) }
	filesMatching("**/*.html") { // or whatever the files are, can be a list of patterns too
		filter(mapOf("tokens" to replacements), org.apache.tools.ant.filters.ReplaceTokens::class.java)
	}
}
```
\+ `__KTLINT_VERSION__` &rarr; `@KTLINT_VERSION@`, because that's how `ReplaceTokens` formats placeholders, OR:
```
mapOf("tokens" to replacements, "beginToken" to "__", "endToken" to "__")
```
but I think the default is KISS-er.

2023-05-16 19:25 UTC, marschwar commented on detekt-generator/build.gradle.kts
> +val copyRuleDocsToWebsite by tasks.registering(CopyDirTask::class) {
Thank you, I will give it a try.

2023-05-16 22:01 UTC, 3flex commented on detekt-generator/build.gradle.kts
> +val copyRuleDocsToWebsite by tasks.registering(CopyDirTask::class) {
Yeah this was going to be my feedback too, we don't need a custom task for this and should use Copy or Sync.

2023-05-16 22:04 UTC, 3flex commented
What do you think about using detekt-generator to do the search/replace instead of using a Gradle task for it?

2023-05-17 18:27 UTC, marschwar commented
That also was my first thought. This would have to be done either in 
* `RuleSetPagePrinter` and `RuleSetPrinter` or 
* `RuleSetProviderVisitor` and `RuleVisitor`.

Both options seem counter intuitive to include templating support. On top of that, I could not think of a clever way to expose the current ktlint version to the kotlin code other than environment variables which feels very brittle. 

That is how I ended up with the gradle solution.

2023-05-17 19:17 UTC, marschwar commented
You are right. That would work. I still like the post processing with gradle better. It is more flexible and neither the printers nor the collectors feel like the right spot.

2023-05-17 19:20 UTC, TWiStErRob commented
Yeah, I trust you on that part, not familiar with those classes.

2023-05-20 12:14 UTC, cortinico requested changes

2023-05-20 12:14 UTC, cortinico commented on detekt-generator/build.gradle.kts
> +val copyRuleDocsToWebsite by tasks.registering(Sync::class) {
Let's not do this.

I would rather act on the file `DocumentationCollector.kt`.
That's where we extract `<compliant>` tags and the description.

There we simply pass the description as it is. I would rather introduce a new tag called `<ktlintversion/>` that gets processed inside `DocumentationCollector.kt`.

Here you just need to pass a parameter like `--ktlint-version` or you can generify and have a `--replacement-map` which accepts a key value list nd map `ktlintversion` to `libs.versions.ktlint.get()`

2023-05-20 12:15 UTC, cortinico commented on detekt-generator/build.gradle.kts
> +val copyRuleDocsToWebsite by tasks.registering(Sync::class) {
oops I just saw the other comments above my bad.

2023-05-20 16:42 UTC, marschwar commented on detekt-generator/build.gradle.kts
> +val copyRuleDocsToWebsite by tasks.registering(Sync::class) {
If you all prefer to do it in the collector, I can do that as well.

2023-05-20 19:34 UTC, TWiStErRob commented on detekt-generator/build.gradle.kts
> +val copyRuleDocsToWebsite by tasks.registering(Sync::class) {
Had a quick look, I think it could fit there too. Only the dependency injection is tricky as it has to go through a few layers, but that's kind of normal I think.

2023-07-01 20:31 UTC, marschwar commented
I removed the custom task added replacements to the docs generation.

2023-07-09 16:40 UTC, marschwar commented
@cortinico should I rebase or close this? I removed the implementation that used gradle and added the functionality to the generator.

2023-07-14 00:15 UTC, cortinico approved these changes
Sorry for the late review @marschwar 
I think we can merge this one, I like the way how you implemented it on the Gradle layer

2023-07-15 23:46 UTC, 3flex requested changes
There are a few new rules added by #6253 which will be merged momentarily... can this be rebased please, and the updates made to the four new rules as well? Thanks, and apologies for the last minute request!

2023-07-16 16:53 UTC, marschwar commented
> There are a few new rules added by #6253 which will be merged momentarily... can this be rebased please, and the updates made to the four new rules as well? Thanks, and apologies for the last minute request!

No woriies. I saw the PR and knew it was coming ;)

2023-07-16 23:23 UTC, 3flex approved these changes

2023-07-17 05:06 UTC, merged