Replaced "threshold" property of ComplexCondition rule by "allowedComplexity"
detekt/detekt pull request #6187
Opened 2023-06-06 20:19 UTC by PoisonedYouth

The ComplexCondition rule reported an issue when the complexity is greater or equal the value defined for the "threshold" property. It is intended that the value defined in the rule is the maximum allowed complexity. So the property is renamed to "allowedComplexity" and the check for reporting an issue is changed to check only for greater, no longer for equal.

The origin issue is https://github.com/detekt/detekt/issues/3679

2023-06-08 16:43 UTC, schalkms reviewed
Thanks! I just think we should remove the test code comments as seen in my comment.

2023-06-08 16:43 UTC, schalkms commented on detekt-rules-complexity/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/ComplexConditionSpec.kt
> +        // given
I think the tests are so concise. Hence, we don't need the comments to understand the test..
```kotlin
// given // when // then
```

2023-06-08 19:54 UTC, marschwar requested changes

2023-06-08 19:54 UTC, marschwar commented on detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/ComplexCondition.kt
> +    private val allowedComplexity: Int by config(defaultValue = 4)
How about `allowedConditions`? The rule does not check some magical complexity metric but rather counts the number of conditions in an `if` statement.

2023-06-08 19:54 UTC, marschwar commented on detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/ComplexCondition.kt
> +    private val allowedComplexity: Int by config(defaultValue = 4)
Leaving the default at `4` will effectively change the behavior. I suggest changing this to `3`.

2023-06-08 19:54 UTC, marschwar commented on detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/ComplexCondition.kt
> +                            "The defined maximum complexity for conditions is set to '$allowedComplexity'"
```suggestion
                            "The defined maximum number of conditions allowed  is set to '$allowedComplexity'"
```

2023-06-08 19:54 UTC, marschwar commented on detekt-rules-complexity/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/ComplexConditionSpec.kt
> +             }
The code should contain at least one `if` or `while` expression. Here the rule does not even check anything.

2023-06-10 13:52 UTC, PoisonedYouth commented on detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/ComplexCondition.kt
> +    private val allowedComplexity: Int by config(defaultValue = 4)
That's an interesting topic. Until now I didn't change the defaults for the rules I updated. If it is intended to reduce the defaults for all rules I can do this with a separate PR (for the already merged rule updates) and update the existing open PRs.

2023-06-11 10:52 UTC, PoisonedYouth commented on detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/ComplexCondition.kt
> +    private val allowedComplexity: Int by config(defaultValue = 4)
@cortinico what is the decision about this topic? Leaving the default value the same (which changes the behavior) or reducing the default value by 1 (to keep the behavior the same).

2023-06-11 18:44 UTC, marschwar commented on detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/ComplexCondition.kt
> +    private val allowedComplexity: Int by config(defaultValue = 4)
> That's an interesting topic. Until now I didn't change the defaults for the rules I updated. 

For params like allowedLines I would not change it from 600 to 599 and the same goes for arbitrary complexity metrics. But for properties like this I would prefer to keep the behavior the same.

2023-06-12 06:16 UTC, PoisonedYouth commented on detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/ComplexCondition.kt
> +    private val allowedComplexity: Int by config(defaultValue = 4)
I can understand your point but isn't it a general question if the behavior should be the same  (existing code does not report new issues after update) or to have a breaking change?

2023-06-12 06:50 UTC, marschwar commented on detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/ComplexCondition.kt
> +    private val allowedComplexity: Int by config(defaultValue = 4)
To me this is more about providing sensitive defaults. Ideally most detekt users do not have to customize the rules. 

If you think 4 conditions in a statement should be allowed because the cognitive complexity is still low enough, that's a discussion we can have. Maybe there was a discussion at the time about how to set the default. I have not checked.

2023-06-12 06:53 UTC, marschwar commented
Can you please not amend and force push. It makes reviewing much harder. The branch will be squash merged later.

2023-06-12 07:08 UTC, marschwar commented on detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/ComplexCondition.kt
> +    private val allowedComplexity: Int by config(defaultValue = 4)
Ok, I did check :)

See https://github.com/detekt/detekt/commit/0d45abd756a6daf6cf78c17ae14d299a9081b475

2023-06-12 08:16 UTC, PoisonedYouth commented on detekt-rules-complexity/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/ComplexCondition.kt
> +    private val allowedComplexity: Int by config(defaultValue = 4)
Thanks I will update the default.

2023-06-12 09:45 UTC, marschwar approved these changes

2023-08-13 08:19 UTC, BraisGabin approved these changes

2023-08-13 08:19 UTC, merged