Fix type in compiler plugin docs
detekt/detekt pull request #6226
Opened 2023-06-16 13:37 UTC by remcomokveld

2023-06-16 15:32 UTC, BraisGabin submitted a review, later dismissed

2023-06-16 15:34 UTC, BraisGabin commented on website/versioned_docs/version-1.23.0/gettingstarted/compilerplugin.mdx
> +1. The rule `InvalidPackageDeclaration` is known to not be working well with the Compiler Plugin [#5747](https://github.com/detekt/detekt/issues/5747).
Could you also make this change in the no versioned documentation? Otherwise for the next version of detekt we will introduce the same typo 😅

2023-06-19 22:42 UTC, 3flex requested changes
Thanks for this! Please make the change requested in https://github.com/detekt/detekt/pull/6226#discussion_r1232408253 and we can merge.

2023-06-20 13:29 UTC, remcomokveld commented
Actually looks like it is already fixed there https://github.com/remcomokveld/detekt/blame/fbb07b08cb6e161d318e56ac5a7a9585ddc04d30/website/docs/gettingstarted/compilerplugin.mdx#L105

2023-06-20 13:29 UTC, closed without merging