Update documentation on how to pin detekt to a supported kotlin version
detekt/detekt pull request #6647
Opened 2023-11-24 15:16 UTC by mlanglet

2023-11-24 15:38 UTC, cortinico commented on website/docs/gettingstarted/gradle.mdx
> +    configurations["detekt"].resolutionStrategy.eachDependency {
I'm unsure this is correct, where you got it from?

2023-11-24 22:52 UTC, 3flex commented on website/docs/gettingstarted/gradle.mdx
> +    configurations["detekt"].resolutionStrategy.eachDependency {
Agree with this comment. Using `afterEvaluate` is not recommended on general and should not be used as an example in our documentation.

2023-11-24 22:53 UTC, 3flex requested changes
See inline comments.

2023-11-25 09:54 UTC, mlanglet commented on website/docs/gettingstarted/gradle.mdx
> +    configurations["detekt"].resolutionStrategy.eachDependency {
I see, thanks for your feedback!

I found the first suggested workaround in [this ](https://github.com/detekt/detekt/issues/6198) issue and applied it to our project because renovatebot was making me go crazy with the failed builds. It fixed it for our project and I thought I'd update the docs linked to from the error during the build since it didn't help me resolve the issue, to help others from not having to dig through issues to find a workaround.

Clearly I should have read the rest of the issue as it is now apparent that documentation for this workaround should be changed and scoped to situation at hand, ie. that the combination of the gradle spring dependencies and spring boot plugin causes an override of the detekt kotlin version. 

I'll update the PR accordingly. My main goal was to make a workaround available at the first site people land on when clicking the link in the failed build log.

2023-12-22 10:39 UTC, closed without merging