EmptyKtFile : add ability to ignore package statements
detekt/detekt pull request #6790
Opened 2024-01-02 15:10 UTC by mgroth0

Fixes https://github.com/detekt/detekt/issues/6788

2024-01-03 08:57 UTC, cortinico commented on detekt-rules-empty/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyKotlinFile.kt
> +    private val ignorePackageDeclaration = config.valueOrDefault(
This config needs documentation

2024-01-03 08:58 UTC, cortinico requested changes
Please fix also the comments that has been reported by the code-scanning on your test file

2024-01-03 10:01 UTC, BraisGabin commented on detekt-rules-empty/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyKotlinFile.kt
> +    private val ignorePackageDeclaration = config.valueOrDefault(
I'd directly remove the configuration. A file with only a package name is an empty file.

2024-01-03 19:26 UTC, cortinico commented on detekt-rules-empty/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyKotlinFile.kt
> +    private val ignorePackageDeclaration = config.valueOrDefault(
I don't have a strong opinion on hardcoding this to true. I can't think of valid use cases for when this would happen. Maybe @mgroth0 has more practical examples?

2024-01-10 08:19 UTC, BraisGabin approved these changes
I hope that with my suggestions CI will be happy.

2024-01-10 08:19 UTC, BraisGabin commented on detekt-rules-empty/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyKotlinFileSpec.kt
> +            package my.package
```suggestion
            package my.packagee
```

2024-01-10 08:19 UTC, BraisGabin commented on detekt-rules-empty/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyKotlinFileSpec.kt
> +            package my.package
`package` is a reserved word, and for that reason this code doesn't compile

```suggestion
            package my.packagee
```

2024-01-10 08:19 UTC, BraisGabin commented on detekt-rules-empty/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyKotlinFileSpec.kt
> +        assertThat(subject.compileAndLint(code)).hasSize(1)
I'm not 100% sure why an empty file doesn't compile but that's not an issue for this PR. It's safe to just run the lint without compiling it.

```suggestion
        assertThat(subject.lint(code)).hasSize(1)
```

2024-01-10 08:22 UTC, BraisGabin commented
LGTM, waiting for the final review from @cortinico

2024-01-10 08:22 UTC, BraisGabin commented on detekt-rules-empty/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/empty/EmptyKotlinFileSpec.kt
> +import io.gitlab.arturbosch.detekt.test.compileAndLint
```suggestion
import io.gitlab.arturbosch.detekt.test.compileAndLint
import io.gitlab.arturbosch.detekt.test.lint
```

2024-01-13 16:09 UTC, cortinico approved these changes

2024-01-13 16:09 UTC, merged