Move Configuration annotation from internal to public API
detekt/detekt pull request #6805
Opened 2024-01-04 02:55 UTC by 3flex

This should probably always have been public as it's expected to be used in 3rd party rule sets.

2024-01-04 08:40 UTC, BraisGabin approved these changes
This would be another annotation to be moved to the `detekt-generated-api` as I described at https://github.com/detekt/detekt/pull/6807#pullrequestreview-1803713512. Again, probably it is not worth it and it doesn't block this PR.

2024-01-04 20:51 UTC, marschwar commented
Is this really the case? What are the benefits for 3rd party rule authors to use the annotation. It is only used to generate the documentation for the 1st party rules. Or am I missing something?

2024-01-04 20:52 UTC, marschwar requested changes
Is this really the case? What are the benefits for 3rd party rule authors to use the annotation. It is only used to generate the documentation for the 1st party rules. Or am I missing something?

2024-01-05 00:33 UTC, 3flex commented
> It is only used to generate the documentation for the 1st party rules

It should be available for third party rules to use as well so they can also generate documentation.

2024-01-05 08:08 UTC, marschwar approved these changes

2024-01-06 05:53 UTC, merged