Move from gradle/gradle-build-action to gradle/actions/setup-gradle
detekt/detekt pull request #6912
Opened 2024-01-26 22:25 UTC by BraisGabin

The new version of `gradle/gradle-build-action` is deprecated and they recommend to use `gradle/actions/setup-gradle`

2024-01-27 06:03 UTC, 3flex requested changes
v3 is an RC so we should not update or change to the new path yet.

2024-01-27 10:02 UTC, TWiStErRob commented
* Related https://github.com/detekt/sarif4k/pull/81

2024-01-27 10:03 UTC, TWiStErRob commented on .github/workflows/codecoverage.yaml
> +        uses: gradle/actions/setup-gradle@v3
You can grab the hash manually from the tag, one less PR to manage.

2024-01-27 10:05 UTC, TWiStErRob commented
> v3 is an RC so we should not update or change to the new path yet.

I would expect a stable release in a week or so, beta were churned out quite fast.

Note: v3 tag is there, so Renovate will think it's stable! Good that @BraisGabin closed https://github.com/detekt/detekt/pull/6911.

2024-01-27 10:06 UTC, TWiStErRob approved these changes
Pending stable release.

2024-01-31 20:32 UTC, 3flex commented
Final version of v3 is released.

> I assume that renovate bot will change the version with a hash once this is merged.

I'm not sure if that's true or not, should confirm before merging.

2024-01-31 21:43 UTC, TWiStErRob commented
> > I assume that renovate bot will change the version with a hash once this is merged.

> I'm not sure if that's true or not, should confirm before merging.

Renovate will pin the action to `@hash # v3`, because of
https://github.com/detekt/detekt/blob/164e15fd7cb336d70bffd9030c4a9c8b4eff4d73/.renovaterc.json#L5

2024-01-31 21:45 UTC, TWiStErRob commented on .github/workflows/codecoverage.yaml
> +        uses: gradle/actions/setup-gradle@v3
this will be the exact line if Renovate pins it back:

```suggestion
        uses: gradle/actions/setup-gradle@aff52e5be96935327d77c5529075184377dc4371 # v3
```

2024-01-31 21:46 UTC, TWiStErRob commented on .github/workflows/codecoverage.yaml
> +        uses: gradle/actions/setup-gradle@v3
Proof https://github.com/MythicDrops/mythicdrops-gradle-plugin/commit/3a6fcf9443b75af435b1fa3c211c2d6cc8145f51#diff-0d634959c8276ae976e39ba475e63d0b9ec27824470c79f1971f58fe37c46325R50

2024-01-31 22:53 UTC, 3flex commented
I'll just merge then and let Renovate fix it

2024-01-31 22:53 UTC, 3flex approved these changes

2024-01-31 22:53 UTC, merged

2024-01-31 23:02 UTC, 3flex commented
Pinning done in #6929

2024-01-31 23:05 UTC, 3flex commented on .github/workflows/codecoverage.yaml
> +        uses: gradle/actions/setup-gradle@v3
Just FYI that hash is for 3.0.0-rc.2.

The PR Renovate opened uses the correct hash for v3 final.

2024-01-31 23:06 UTC, TWiStErRob commented on .github/workflows/codecoverage.yaml
> +        uses: gradle/actions/setup-gradle@v3
haha :D, yeah I got confused by the GitHub UI:
https://github.com/gradle/actions/issues/10