Enable gradle worker api
detekt/detekt pull request #6913
Opened 2024-01-26 23:02 UTC by BraisGabin

Closes #6887

To get the reasoning behind this change read the related issue.

2024-02-11 04:13 UTC, 3flex requested changes
Maybe hold off, see #6964 and https://github.com/gradle/gradle/issues/28034

2024-02-25 23:14 UTC, 3flex commented
Do you want to update the report merge docs to say that the worker API should be disabled if using the report merge feature? Then we can merge.

2024-03-01 11:41 UTC, BraisGabin commented
I was checking thy this failed on jdk11 and jdk8. And I found this: https://ge.detekt.dev/s/6lrnem2j7n3qs/tests/overview?outcome=FAILED

Two tests failed because of, I assume, https://github.com/gradle/gradle/issues/28034. So it seems that https://github.com/gradle/gradle/issues/28034 is related with the JDK version.

And the other one seems that we don't support the worker API on old versions of gradle: https://ge.detekt.dev/s/6lrnem2j7n3qs/tests/task/:detekt-gradle-plugin:functionalTest/details/io.gitlab.arturbosch.detekt.GradleVersionSpec/runsOnOldestSupportedGradleVersion()?top-execution=1 Should we check on that or, because this will be released on 2.0.0, move up our min supported version?

2024-03-01 13:30 UTC, BraisGabin commented
I need to find a way to disable Worker API for the merge tests otherwise they are not going to pass.

2024-03-08 11:43 UTC, BraisGabin commented on detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt
> +    val defaultValue = isGradleVersionAtLeast(major = 7, minor = 6).toString()
Gradle worker API doesn't work on any version below `7.6` so we don't enable it by default for those versions.

2024-03-09 00:11 UTC, 3flex commented on detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt
> +    val defaultValue = isGradleVersionAtLeast(major = 7, minor = 6).toString()
What changed in 7.6? Or did you discover that through testing? There's nothing in the 7.6 release notes about workers: https://docs.gradle.org/7.6/release-notes.html

2024-03-09 00:12 UTC, 3flex commented on detekt-gradle-plugin/src/testFixtures/kotlin/io/gitlab/arturbosch/detekt/testkit/DslGradleRunner.kt
> +        writeProjectFile(PROPERTIES_FILENAME, propertiesContent)
Instead of writing a properties file you should be able to pass `-Pdetekt.use.worker.api=true/false` as a CLI argument which avoids writing another file just for this.

2024-03-09 17:24 UTC, BraisGabin commented on detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt
> +    val defaultValue = isGradleVersionAtLeast(major = 7, minor = 6).toString()
Yes, I was testing and 7.6 was the first one that work. No idea why it doesn't work on prior versions.

2024-03-09 17:38 UTC, BraisGabin commented on detekt-gradle-plugin/src/testFixtures/kotlin/io/gitlab/arturbosch/detekt/testkit/DslGradleRunner.kt
> +        writeProjectFile(PROPERTIES_FILENAME, propertiesContent)
Done

2024-03-09 17:39 UTC, BraisGabin commented on detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt
> +    val defaultValue = isGradleVersionAtLeast(major = 7, minor = 6).toString()
Probably we should look at this and fix it. But I think that is a different issue.

2024-03-11 00:12 UTC, 3flex commented on detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt
> +import org.jetbrains.kotlin.gradle.utils.isGradleVersionAtLeast
Sorry I didn't pick this up earlier, but you should use the Gradle methods for version comparison instead of this utility method in KGP:

`GradleVersion.current() >= GradleVersion.version("7.6")`

2024-03-11 00:16 UTC, 3flex commented on detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt
> +    val defaultValue = isGradleVersionAtLeast(major = 7, minor = 6).toString()
I'm 99% sure this is an issue with our test setup and not a problem with this PR. Gradle is passing a Gradle plugin variant that's compatible with Gradle 8.2+ which fails in some scenarios on this earlier Gradle version. I ran into this in #7025 and #6489.

I'll open a new PR to address it.

2024-03-11 02:05 UTC, 3flex commented on detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt
> +    val defaultValue = isGradleVersionAtLeast(major = 7, minor = 6).toString()
Should be fixed by #7036. I've also rebased #6489 on top of #7036 to prove that it works (functional tests used to fail because of a similar issue).

2024-03-11 02:06 UTC, 3flex commented on detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt
> +import org.jetbrains.kotlin.gradle.utils.isGradleVersionAtLeast
Though as mentioned in the other comment this version check shouldn't be required at all.

2024-03-12 11:31 UTC, BraisGabin commented on detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt
> +import org.jetbrains.kotlin.gradle.utils.isGradleVersionAtLeast
Removed

2024-03-12 11:32 UTC, BraisGabin commented on detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt
> +    val defaultValue = isGradleVersionAtLeast(major = 7, minor = 6).toString()
This code was removed, now Worker API is always enabled by default.

2024-03-12 21:20 UTC, 3flex commented
Annoying the build is still failing. I saw this in the log:

```
    w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
        /home/runner/.gradle/wrapper/dists/gradle-6.8.3-bin/7ykxq50lst7lb7wx1nijpicxn/gradle-6.8.3/lib/kotlin-stdlib-1.4.20.jar (version 1.4)
        /home/runner/.gradle/wrapper/dists/gradle-6.8.3-bin/7ykxq50lst7lb7wx1nijpicxn/gradle-6.8.3/lib/kotlin-stdlib-common-1.4.20.jar (version 1.4)
        /home/runner/.gradle/wrapper/dists/gradle-6.8.3-bin/7ykxq50lst7lb7wx1nijpicxn/gradle-6.8.3/lib/kotlin-stdlib-jdk7-1.4.20.jar (version 1.4)
        /home/runner/.gradle/wrapper/dists/gradle-6.8.3-bin/7ykxq50lst7lb7wx1nijpicxn/gradle-6.8.3/lib/kotlin-stdlib-jdk8-1.4.20.jar (version 1.4)
        /home/runner/.gradle/wrapper/dists/gradle-6.8.3-bin/7ykxq50lst7lb7wx1nijpicxn/gradle-6.8.3/lib/kotlin-reflect-1.4.20.jar (version 1.4)
        /home/runner/work/detekt/detekt/detekt-gradle-plugin/build/tmp/functionalTestMinSupportedGradle/work/.gradle-test-kit/caches/jars-8/06130c2f1c60b901150c43a397642dca/kotlin-stdlib-1.9.20.jar (version 1.9)
        /home/runner/work/detekt/detekt/detekt-gradle-plugin/build/tmp/functionalTestMinSupportedGradle/work/.gradle-test-kit/caches/jars-8/a369b37b4f997a63d005d4a5f51fd41f/kotlin-reflect-1.9.20.jar (version 1.9)
```

So my fix is incomplete but it's strange that this is only occurring in this PR and not on `main`

2024-03-14 03:55 UTC, 3flex commented on detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt
> +    val defaultValue = isGradleVersionAtLeast(major = 7, minor = 6).toString()
You might need to restore this check.

To isolate the issue I tried using 1.23.5 in a standalone Gradle project running 6.8.3. That failed. The earliest version that worked for me is 7.5. So there's an existing issue unrelated to the Gradle version test split, and not directly related to this PR.

I think enabling where possible with this check restored (changed to 7.5) makes sense but it's odd that it's not working on older versions. The whole point of the process isolation mode is that the worker's classpath is isolated from Gradle's, so the Gradle version shouldn't matter here.

2024-03-14 08:52 UTC, BraisGabin commented on detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt
> +    val defaultValue = isGradleVersionAtLeast(major = 7, minor = 6).toString()
I must say that I'm a bit lost on this regard. I don't fully understand all the picture so it's difficult to me to know what's going on.

I'm going to restore it using `7.5` as the minimum version then :)

2024-03-16 04:36 UTC, 3flex commented
I think I've had a fundamental misunderstanding of what process isolation actually achieves when using workers. The worker still has Gradle runtime in its classpath, which is why there's different behaviour when running with different Gradle versions. In many cases things work, because the Kotlin version on the Gradle classpath doesn't conflict with detekt's, but in other cases there's an issue because of Kotlin runtime behaviour changes and Gradle 6.8 embeds Kotlin 1.4.20.

Worker classloader isolation makes it possible to run tasks with different libraries to the buildscript classpath. Process isolation extends this to allow running tasks with different JDK or system properties to those used for Gradle itself.

Neither of these quite describes what we need to execute detekt.

TL;DR: The current worker implementation includes Gradle's runtime which conflicts with detekt's runtime. The worker implementation needs to change before we can use it.

2024-03-17 06:20 UTC, 3flex requested changes
I'd unfortunately consider this blocked until https://github.com/gradle/gradle/issues/28478 is fixed in Gradle.

2024-03-17 10:05 UTC, BraisGabin commented
After #7060 I'll benchmark these again to see how it behaves.

2024-03-22 12:03 UTC, BraisGabin commented
I move to draft this again, I need to perform benchmarks again (Note for myself)

2025-08-20 21:40 UTC, closed without merging