Cli provide list of files
detekt/detekt pull request #7007
Opened 2024-03-02 13:00 UTC by BraisGabin

This is just the first step. Now the `cli` never provides a list of files. This will simplify A LOT the core. But that simplification will be don in next prs. `cli` still uses `PathFilters`, in future PRs I'll check that.

Related with #6866

2024-03-08 21:34 UTC, 3flex commented on detekt-cli/src/test/kotlin/io/gitlab/arturbosch/detekt/cli/CliArgsSpec.kt
> +        private val pathCliArgs = Path("src/main/kotlin/io/gitlab/arturbosch/detekt/cli/CliArgs.kt").absolute()
Related to my other comment, I don't think these should be passed as absolute paths in tests.

2024-03-18 07:33 UTC, 3flex requested changes
See inline comments - particularly the one for path filtering.

2024-03-22 13:37 UTC, BraisGabin commented on detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/Spec.kt
> +                .filter { pathFilters?.isIgnored(it) != false }
You are right, I should not use the absolute path. I change it. What do you think about this implementation (I did the changes on the last commit to make them easier to review)

2024-03-22 13:39 UTC, BraisGabin commented on detekt-cli/src/test/kotlin/io/gitlab/arturbosch/detekt/cli/CliArgsSpec.kt
> +        private val pathCliArgs = Path("src/main/kotlin/io/gitlab/arturbosch/detekt/cli/CliArgs.kt").absolute()
I don't understand this. The `cli` should pass absolute paths to the core. And these variables are used to help me ensure that the correct files are passed.

2024-03-22 13:54 UTC, BraisGabin commented
I broke something... I need to check.

2024-03-25 08:50 UTC, BraisGabin commented on config/detekt/argsfile
> +**/resources/**,detekt*/build/**,build-logic/build/**,build-logic/bin/**
Now that we don't take into account the absolute path when you provide excludes/includes you need to be more careful with the initial `**/`. `**/` match at least one directory. If your directory on the basePath then it doesn't match. For that reason I needed to update these excludes.

2024-03-25 10:55 UTC, 3flex commented on config/detekt/argsfile
> +**/resources/**,detekt*/build/**,build-logic/build/**,build-logic/bin/**
>  If your directory on the basePath then it doesn't match

This will need to be called out loud & clear in the release notes - I also don't recall if basepath is always set but we should make sure it's always set to a reasonable default value by default.

2024-03-25 11:09 UTC, 3flex commented on config/detekt/argsfile
> +**/resources/**,detekt*/build/**,build-logic/build/**,build-logic/bin/**
(it's the right thing to do though!)

2024-03-25 11:59 UTC, BraisGabin commented on config/detekt/argsfile
> +**/resources/**,detekt*/build/**,build-logic/build/**,build-logic/bin/**
About default values for `bashPath`:

- `cli` uses the working directory.
- `gradlePlugin` as far as I saw it passes the project path.

Both of them seems like good default values to me.

---

And about call out this change, I agree. This is a breaking change on the `cli`. But I'm not sure what can I do now about it.

2024-04-03 09:06 UTC, 3flex approved these changes

2024-04-03 14:38 UTC, merged