Check for root of receiver in selector expression
detekt/detekt pull request #7220
Opened 2024-04-23 19:02 UTC by atulgpt

Fixes https://github.com/detekt/detekt/issues/6373

2024-05-06 16:50 UTC, cortinico requested changes

2024-05-06 16:50 UTC, cortinico commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/VarCouldBeVal.kt
> +                    ?.resultingDescriptor
Why are you changing this?

2024-05-06 16:50 UTC, cortinico commented on detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/NullCheckOnMutableProperty.kt
> +                    }
Same as other comment. Looks like this change is unnecessary (let's move it to another PR?)

2024-05-06 16:50 UTC, cortinico commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryLet.kt
> +    val dialog: Dialog? = null
This should go

2024-05-07 09:55 UTC, atulgpt commented on detekt-rules-errorprone/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/NullCheckOnMutableProperty.kt
> +                    }
With this rule, this code is started flagging. As we have written the code as `<expression>?.let { it.<someOtherNullableChain> }` that could be simplified as `<expression>?.<someOtherNullableChain>`

2024-05-07 09:56 UTC, atulgpt commented on detekt-rules-style/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/VarCouldBeVal.kt
> +                    ?.resultingDescriptor
Same comment

> With this rule, this code is started flagging. As we have written the code as `<expression>?.let { it.<someOtherNullableChain> }` that could be simplified as `<expression>?.<someOtherNullableChain>`

2024-07-13 11:17 UTC, cortinico approved these changes
LGTM 👍 sorry for the late reply.

2024-07-28 13:20 UTC, BraisGabin approved these changes

2024-07-28 13:20 UTC, merged