Remove `ThresholdedCodeSmell`
detekt/detekt pull request #7592
Opened 2024-08-28 21:46 UTC by BraisGabin

Right now `CodeSmell` is an `open class` and I will like to remove the `open` from it. #7591 removes `CorrectableCodeSmell` and `ThresholdedCodeSmell` was the other extension of `CodeSmell`.

This is the "short" implementation for this. Just remove the "extra" features of `ThresholdedCodeSmell` because, I think, no one uses them. There is another option. I plan to add a way to add extra information inside a `CodeSmell`. Something like:

```kotlin
CodeSmell(
  ...
  extra: Map<String, String>(),
)
```

So I could replace `Metric(value = 5, threshold = 4)` for something like: `extra = mapOf("value" to "5", "threshold" to "4")`. But I think that this change will give little value (replacing Metrics instead of removing it).

2024-08-29 10:02 UTC, cortinico requested changes

2024-08-29 10:02 UTC, cortinico commented on detekt-rules-complexity/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/CyclomaticComplexMethodSpec.kt
>          }
Now you have `three` in the test title, but not in the test body.

2024-08-29 10:02 UTC, cortinico commented on detekt-rules-complexity/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/CyclomaticComplexMethodSpec.kt
> +private fun assertExpectedComplexityValue(code: String, config: TestConfig) {
This should probably be renamed now

2024-09-03 08:34 UTC, BraisGabin commented on detekt-rules-complexity/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/CyclomaticComplexMethodSpec.kt
>          }
I added back this assert. I can still assert the same thing using the finding message.

2024-09-03 08:34 UTC, BraisGabin commented on detekt-rules-complexity/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/CyclomaticComplexMethodSpec.kt
> +private fun assertExpectedComplexityValue(code: String, config: TestConfig) {
I reverted this change.

2024-09-06 10:43 UTC, cortinico approved these changes

2024-09-07 10:31 UTC, merged