Fix redundant empty tags in baseline XML
detekt/detekt pull request #7625
Opened 2024-09-11 21:56 UTC by JordanLongstaff

Fixes #7622

The `CurrentIssues` tag is reduced to a self-closing tag if there are no current issues.
The `ManuallySuppressedIssues` tag is removed entirely if there are no manually suppressed issues.

2024-09-12 11:09 UTC, cortinico requested changes

2024-09-12 11:09 UTC, cortinico commented on detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/baseline/BaselineFormat.kt
>                  }
You should `writeEmptyElement(MANUALLY_SUPPRESSED_ISSUES)` here as well

2024-09-13 00:09 UTC, cortinico approved these changes

2024-09-13 06:55 UTC, merged

2024-09-13 06:55 UTC, BraisGabin commented
Thanks for the pr