[7465] Rename RequiresTypeResolution to RequiresFullAnalysis
detekt/detekt pull request #7627
Opened 2024-09-12 16:34 UTC by alXmas

Fixes: https://github.com/detekt/detekt/issues/7465

2024-09-13 07:14 UTC, 3flex commented
Both will require doc updates too.

2024-09-13 07:22 UTC, BraisGabin commented
I'm still not fully on board with my pr so if @ this one updates the docs I'm OK with merging this before.

2024-09-13 11:14 UTC, alXmas commented
> Warnings
> ⚠️ 	
> 
> It looks like you're editing the **un-versioned copy** of our website. This affects only users on the 'next' version of detekt, and it's correct only if you intend to document a **future change or feature**. If you intended to make a change also for the **current** version of detekt, please make sure you edit the equivalent file inside `website/versioned_docs/` as well.
> 	Messages
> 📖 	
> 
> Thank you very much for making [our website](https://detekt.dev/) better ❤️!
> 
> Generated by 🚫 [dangerJS](https://danger.systems/js) against [b331865](https://github.com/detekt/detekt/commit/b331865c1227108e3506504403866acc781a629f)

I run `yarn generate-and-build` in website folder, but nothing added/updated :(

2024-09-13 16:36 UTC, cortinico requested changes

2024-09-13 16:36 UTC, cortinico commented on website/src/pages/changelog.md
> -    -   We will now skip rules annotated with `@RequiresTypeResolution` when without Type Resolution - [#5176](https://github.com/detekt/detekt/pull/5176)
Please undo the changes to the CHANGELOG file

2024-09-13 16:37 UTC, cortinico commented
> I run `yarn generate-and-build` in website folder, but nothing added/updated :(

You can disregard the warning this time as you actually need to update **only** the unversioned docs (they will appear once 2.x is out)

2024-09-14 16:19 UTC, alXmas commented on website/src/pages/changelog.md
> -    -   We will now skip rules annotated with `@RequiresTypeResolution` when without Type Resolution - [#5176](https://github.com/detekt/detekt/pull/5176)
Fixed! :)

2024-09-16 10:20 UTC, cortinico approved these changes

2024-09-16 14:24 UTC, BraisGabin approved these changes

2024-09-16 14:44 UTC, merged